ministryofjustice/prisoner-content-hub-backend

- composer.json
- composer.lock
- sites/default/settings.php
This PR is for https://trello.com/c/M9VPg3Dx/934-enable-file-hosting-for-drupal-in-cloud-platform-s3.
> This has been ported from https://github.com/ministryofjustice/digital-hub/pull/715#issue-432982936
To develop/deploy this the following steps need to have been applied in your environment:
1. Ensure the Docker image has been built (i.e. the container being used for Drupal has Flysystem installed).
2. Visit `/admin/modules` and enable both `Flysystem` and `Flysystem S3`. You need to click "install" once you've ticked them...
3. Add the following environment variables to your Drupal instance (I've been using https://github.com/ministryofjustice/digital-hub/pull/714 and dropping them in `drupal.env`:
> The values can be retrieved from our Cloud Platform secrets following …
> Add Flysystem S3 dependency and configuration to Drupal

- helm_deploy/prisoner-content-hub-backend/readme.md
- helm_deploy/prisoner-content-hub-backend/secrets.example.yaml
- helm_deploy/prisoner-content-hub-backend/templates/_helpers.tpl
- helm_deploy/prisoner-content-hub-backend/templates/deployment.yaml
- helm_deploy/prisoner-content-hub-backend/values.local.yaml
- helm_deploy/prisoner-content-hub-backend/values.prod.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
- Split configuration by usage
- Update helpers to template ES host
- Add readme
> Update Helm Chart

- helm_deploy/prisoner-content-hub-backend/templates/ingress.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
- Add annotations as suggested here https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/modsecurity.html\#ingress-annotations
> Add CP security to Ingress

- .circleci/config.yml
- Add command for releases using Helm
- Add release_production job
- Udpate workflow to include gated release job
> Update CircleCI configuration for releases

- Dockerfile
- composer.json
- composer.lock
Reverts ministryofjustice/prisoner-content-hub-backend#24
> Revert "Import Flysystem patch to migrate fields to Flysystem"

- modules/custom/moj_resources/src/ContentApiClass.php
- modules/custom/moj_resources/src/SeriesContentApiClass.php
- modules/custom/moj_video_item/moj_video_item.install
- modules/custom/moj_video_item/moj_video_item.module
- modules/custom/moj_video_item/src/Normalizer/VideoNormalizer.php
- sites/default/settings.php
**To apply**
- Clear caches
- Remove deleted field data (Old data threw errors whilst testing)
- Run `/update.php`
> Add migration to transfer Video to File field type

- helm_deploy/prisoner-content-hub-backend/templates/deployment.yaml
- sites/default/settings.php
- Update Helm deployment
- Update settings.php to use new environment variables
- Make environment variable names more meaningful
> Make Flysytsem CNAME setting configurable in Helm

- sites/default/settings.php
Reverts ministryofjustice/prisoner-content-hub-backend#38
> Revert "Set Flysystem prefix"

- helm_deploy/prisoner-content-hub-backend/values.yaml
This fixes the issues with uploading files to S3 using flysystem in Drupal
- Remove the capabilities block
- Update the fsGroup for volume mount
> Remove capabilities block from Security Context in Helm

- helm_deploy/prisoner-content-hub-backend/values.yaml
- Add VPN CIDR to whitelist
- Add no robots headers to responses
> Configure Nginx ingress

- helm_deploy/prisoner-content-hub-backend/templates/ingress.yaml
- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
This PR:
- Adds a custom hostname for the frontend
- Refactors the ingress slightly to allow multiple hostnames
> Add custom hostnames

- Dockerfile
- composer.json
- composer.lock
- Update Drupal to 8.9.1
- Update dependencies to latest
- Update DockerFile base image for Drupal 8.9.1
** Notes **
The following will need to be completed when upgrading the Docker image
- Disable Contact Module
- Clear caches from the database
- Install the new Docker image
- Run /update.php
> Update Drupal and dependencies

- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
Added hostname to ingress values, this is used for generating the external file URL
> Add hostname to ingress values

- .gitignore
- Dockerfile
- composer.json
- composer.lock
- helm_deploy/prisoner-content-hub-backend/templates/deployment.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
- patches/flysystem_s3_8.x-1.0-beta1_enable_pre-signed_downloads.patch
- sites/default/settings.php
- Add patch to enable pre-signed links in Flysystem
- Update Composer JSON to apply patches
- Update Compose lock file
- Update Drupal to 8.9.2
- Update gitignore
> Add Flysystem pre-signed links

- modules/custom/moj_resources/src/NewFeaturedContentApiClass.php
- modules/custom/moj_resources/src/Plugin/rest/resource/NewFeaturedContentResource.php
- Not used in the API despite talking it as an arg, removed
- Remove from all calls to API
> Remove category arg from NewFeaturedContent endpoint

- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.local.yaml
- Set Dev to use Always, this will support using the preview tag
- Set Local to use Never, allowing the use of local Docker builds
> Update Kubernetes image pull policy

- README.txt
- composer.json
- composer.lock
- helm_deploy/prisoner-content-hub-backend/values.yaml
- patches/flysystem_s3_2.0.0-rc1_enable_pre-signed_downloads.patch
- Removed flysystem_s3 v1
- Added flysystem_s3 v2
- Used updated patch for pre-signed downloads
> Update flysystem_s3, add pre-signed downloads

- modules/custom/moj_resources/src/CategoryFeaturedContentApiClass.php
- modules/custom/moj_resources/src/Plugin/rest/resource/ContentResource.php
- modules/custom/moj_resources/src/RelatedContentApiClass.php
- modules/custom/moj_resources/src/SeriesContentApiClass.php
- modules/custom/moj_resources/src/TermApiClass.php
- Notice: Undefined property: Drupal\moj_resources\Plugin\rest\resource\NewFeaturedContentResource:: in Drupal\moj_resources\Plugin\rest\resource\NewFeaturedContentResource->get() (line 119 of /var/www/html/modules/custom/moj_resources/src/Plugin/rest/resource/NewFeaturedContentResource.php)
- Notice: Undefined variable: lang in Drupal\moj_resources\Plugin\rest\resource\ContentResource->get() (line 119 of /var/www/html/modules/custom/moj_resources/src/Plugin/rest/resource/ContentResource.php)
- Notice: Trying to get property 'value' of non-object in Drupal\moj_resources\CategoryFeaturedContentApiClass->Drupal\moj_resources\{closure}() (line 98 of /var/www/html/modules/custom/moj_resources/src/CategoryFeaturedContentApiClass.php)
- Notice: Trying to get property 'changed' of non-object in …
> Fix error messages identified in Drupal logs

- modules/custom/moj_resources/src/ContentApiClass.php
- modules/custom/moj_resources/src/Plugin/rest/resource/ContentResource.php
- modules/custom/moj_resources/src/Utils.php
- Create new function for checking prison id
- Accept prison id in api
> Allow filtering by prison

- helm_deploy/prisoner-content-hub-backend/values.yaml
- modules/custom/moj_healthcheck/src/Plugin/rest/resource/HealthResource.php
This may need some tweaks internally in the Drupal admin area.
> Move API health endpoint to /health

- helm_deploy/prisoner-content-hub-backend/values.yaml
- Move health checks back to /health
> Put liveness/readiness to proper health check

- apache/apache2.conf
- apache/sites-enabled/hub-be.conf
- composer.json
- composer.lock
- sites/default/services.yml
- Redirect WatchDog logs to STDOUT/ERR
- Configure Apache to not log requests for assets
> Install and configure MonoLog

- Dockerfile
- Response to breaking changes to Plugin API in v2
> Add version lock to Composer install step in Docker

- modules/custom/moj_resources/src/CategoryMenuApiClass.php
- modules/custom/moj_resources/src/Plugin/rest/resource/CategoryMenuResource.php
- Refactored code
- Redid logic around returning results to simplify it
> Refactor category menu endpoint

- modules/custom/moj_resources/src/CategoryFeaturedContentApiClass.php
- modules/custom/moj_resources/src/Plugin/rest/resource/CategoryFeaturedContentResource.php
refactor variable names in API Class and content resource
> Refactor category featured content API endpoint

- modules/custom/moj_resources/src/Plugin/rest/resource/VocabularyResource.php
- modules/custom/moj_resources/src/VocabularyApiClass.php
While we currently just use this for secondary tags, it's a generic endpoint that can return any taxonomy so we should add filtering.
> Refactor Vocabulary endpoint

- composer.json
- composer.lock
- sites/default/default.settings.php
> What changes are included in the PR. How do they affect user behaviour, technical debt, etc.
> Link to the Trello card this work relates to (or describe why a card isn't appropriate), e.g. "Fixes (Trello card URL)".
Trello cards: 
- https://trello.com/c/m48bNKes/1724-get-drush-working-so-we-can-programmatically-reinstall-modules-and-do-data-migrations.
- https://trello.com/c/eBTX67RF/63-update-drupal-and-dependencies
This PR introduces Drush, a PHP/Drupal task runner:
> Why do we want to make this change?
We've got a few use-cases for Drush:
- Reinstalling modules as part of a Helm deployment
- Upgrading Drupal
- Clearing caches and developing locally
- Data migrations, such as updating prison categories. This is the big one that'll help us loads as we try to simplify the information …
> Introduce Drush (and update a bunch of dependencies 🙈)

- modules/custom/moj_resources/src/TermApiClass.php
> Fix typo in Term API class

- composer.lock
https://trello.com/c/fOSmRHuT/2012-update-drupal-to-8912-bump-dependencies
Update drupal core to 8.9.13 (current version 8.9.10).
Update other dependencies to latest versions.
`composer update` was run as part of this PR.  This updates everything in the composer.json file, below is the output showing the changes.
```
Gathering patches for dependencies. This might take a minute.
- Updating composer/installers (v1.9.0 => v1.10.0): Loading from cache
- Updating drupal/core-composer-scaffold (8.9.10 => 8.9.13): Loading from cache
- Updating drupal/core-project-message (8.9.10 => 8.9.13): Loading from cache
- Updating drupal/core-vendor-hardening (8.9.10 => 8.9.13): Loading from cache
- Updating webmozart/assert (1.9.1 => 1.10.0): Downloading (100%)
- …
```
> Updating drupal core to 8.9.13

- Makefile
- composer.json
- composer.lock
- config/sync/core.entity_form_display.node.moj_pdf_item.default.yml
- config/sync/core.entity_form_display.node.moj_radio_item.default.yml
- config/sync/core.entity_form_display.node.moj_video_item.default.yml
- config/sync/core.entity_form_display.node.page.default.yml
- config/sync/core.entity_view_display.node.moj_pdf_item.default.yml
- config/sync/core.entity_view_display.node.moj_radio_item.default.yml
- config/sync/core.entity_view_display.node.moj_video_item.default.yml
- config/sync/core.entity_view_display.node.page.default.yml
- config/sync/core.entity_view_display.node.page.search_index.yml
- config/sync/core.entity_view_display.node.page.search_result.yml
- config/sync/core.entity_view_display.node.page.teaser.yml
- config/sync/core.extension.yml
- config/sync/field.field.node.moj_pdf_item.field_release_date.yml
- config/sync/field.field.node.moj_radio_item.field_release_date.yml
- config/sync/field.field.node.moj_video_item.field_release_date.yml
- config/sync/field.field.node.page.field_release_date.yml
- config/sync/field.field.taxonomy_term.series.field_sort_by.yml
- config/sync/field.storage.node.field_release_date.yml
- config/sync/field.storage.taxonomy_term.field_sort_by.yml
- config/sync/views.view.series_taxonomy_term_content_sorting.yml
- docker-compose.circleci.yml
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/prisoner_hub_taxonomy_sorting.deploy.php
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/prisoner_hub_taxonomy_sorting.module
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/src/Controller/PageController.php
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/tests/src/ExistingSiteJavascript/SeriesFieldsFormTest.php
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/tests/src/ExistingSiteJavascript/SeriesFieldsTest.php
- phpunit.xml
https://trello.com/c/h4QLGZyy/36-rename-and-improve-date-field-series-sorting-only
This PR adds the following functionality:
- Introduces two new options to the `field_sort_by` on the series Taxonomy term. _"Release date (newest first)"_ and _"Release date (oldest first)"_
- Renames `field_moj_date` to `field_release_date`.  This is done by creating a new field, hiding the existing field, and copying the contents across.  The previous field will then be removed on a subsequent deployment.
- Use Drupal's javascript form states API, to show/hide the season+episode number and release date fields depending on what series has been selected (and what `field_sort_by` value has been assigned to that series).
- Improve field labels and descriptions as per work …
> 36 Rename date field improve description

- Dockerfile
- composer.lock
No
See https://blog.sonarsource.com/php-supply-chain-attack-on-composer.
> Updating composer to fix security vulnerability

- .circleci/config.yml
Changing ssh key in circle CI so need to update the reference to it in this config
> Updating ssh key

- composer.lock
Updating drupal core (to 8.9.15) and dependencies to include security fixes.
Release notes are here: https://www.drupal.org/project/drupal/releases/8.9.15
> Updating drupal core to 8.9.15

- Dockerfile
- php/xdebug.ini
No, just a small change.
My xdebug stopped working for some unknown reason, updating to version 3 (from version 2) fixed it. 
> Update to xdebug 3.

- composer.lock
No, it's a small change.
Update drupal core to include security fix: https://www.drupal.org/sa-core-2021-005
> Updating drupal core to 9.1.12

- composer.json
- composer.lock
- patches/jsonapi_image_styles-3232157-image-styles-are-generated-for-other-types-of-file-entities-2.patch
No this is a small issue that doesn't need a card.
There is however a issue opened on drupal.org https://www.drupal.org/project/jsonapi_image_styles/issues/3232157
Patch the jsonapi_image_styles module to stop it trying to resize non-image files.  This wasn't actually causing any issues, but creating lots of entries in the logs.
> Fix image resizing applied to other file types

- config/sync/core.entity_form_display.taxonomy_term.series.default.yml
- docroot/modules/custom/prisoner_hub_featured_content/js/prisoner-hub-featured-content.js
Related to tomorrow's release for JSON:API category pages (multiple cards).
Couple of bug fixes that effected the series edit page.
- Fixed a JS error which prevented images from being uploaded
- Hide the old "featured for category" field (to be removed in a future release).
> Fixes for category page release

- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
Adding new ingress annotations to prepare for move to new kubernetes cluster 
https://trello.com/c/6oQHl9AH
New ingresses added.
Need to ensure that we can still access site after releases
> Adding new ingress annotations

- config/sync/user.role.local_administrator.yml
https://trello.com/c/lnfpeut3/426-add-duplicate-content-option-in-drupal
Missed a permission for setting the "Take ownership" option.
> Setting permission for take ownership on entity clone.

- Dockerfile
No it's a small change.
So that code changes are instantly picked up.
> Disable opcache on local environments

- config/sync/field.field.node.moj_pdf_item.field_moj_prisons.yml
- config/sync/field.field.node.moj_radio_item.field_moj_prisons.yml
- config/sync/field.field.node.moj_video_item.field_moj_prisons.yml
- config/sync/field.field.node.page.field_moj_prisons.yml
- config/sync/field.field.taxonomy_term.moj_categories.field_featured_tiles.yml
- config/sync/user.role.moj_local_content_manager.yml
- config/sync/views.view.front_page.yml
- config/sync/views.view.frontpage.yml
- config/sync/views.view.sample_view.yml
- config/sync/views.view.taxonomy_term.yml
There's been a few config changes made on the live site over the last week.  This PR adds them into code so they don't get reverted on the next deployment.
> Update with config from live

- .circleci/config.yml
- helm_deploy/prisoner-content-hub-backend/values.development.yaml
Moving development over to new cluster
> Moving dev over to new cluster

- Makefile
> Removing `build-` prefix

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.deploy.php
https://trello.com/c/8B2Ygfag/567-show-all-content-in-a-category-and-paginate-it
Adds a deploy hook that updates series with missing images to use the image from the most recent episode.
The deployment will print out which series were updated and which ones it couldn't update (due to there not being any images to copy over).
> Adding deploy hook for updating series with missing images.

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.deploy.php
Quick fix for failing tests https://app.circleci.com/pipelines/github/ministryofjustice/prisoner-content-hub-backend/1544/workflows/50813152-a171-4104-a1e2-9f58f152f2f3/jobs/2852
> Reducing batch amount to avoid database errors during deployment.

- composer.json
- composer.lock
- docroot/sites/default/settings.php
- patches/flysystem_2772847-57-presigned-urls.patch
- patches/flysystem_2772847-58-presigned-urls.patch
I've updated the patch we are using for pre-signed s3 urls.  This is in preparation for some upcoming work on the flysystem_s3 module.  
It also fixes:
https://trello.com/c/bD1oEkd0/495-re-instate-drupal-image-resizing-ddos-protection
For more info see https://www.drupal.org/project/flysystem_s3/issues/2772847#comment-14460047
> Updating presigned url patch.

- docroot/modules/custom/prisoner_hub_sub_terms/src/Resource/SubTerms.php
Fixes and issue with https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/390
Empty results were being returned on the new `sub_terms` response.  This was due to how the subclass methods were being overridden.  Not entirely sure why it didn't give an error, but copying over the entire overridden method fixes the issue, (and is probably the more appropriate way to handle it).
> Fixing empty responses by using correct inheritance.

- composer.json
- composer.lock
Output from running `composer update drupal/core-recommended --with-dependencies`
```
Lock file operations: 0 installs, 11 updates, 0 removals
- Upgrading behat/mink (v1.9.0 => v1.10.0)
- Upgrading doctrine/cache (1.12.1 => 1.13.0)
- Upgrading drupal/core (9.3.9 => 9.3.14)
- Upgrading drupal/core-recommended (9.3.9 => 9.3.14)
- Upgrading guzzlehttp/guzzle (6.5.5 => 6.5.6)
- Upgrading phpdocumentor/type-resolver (1.6.0 => 1.6.1)
- Upgrading phpunit/phpunit (9.5.19 => 9.5.20)
- Upgrading sebastian/environment (5.1.3 => 5.1.4)
- Upgrading symfony/dom-crawler (v4.4.39 => v4.4.42)
- Upgrading symfony/finder (v4.4.37 => v4.4.41)
- Upgrading symfony/http-client (v5.4.5 => v5.4.9)
```
Output from running …
> Updating drupal core to 9.3.14, with dependencies.

- docker-compose.circleci.yml
- helm_deploy/prisoner-content-hub-backend/values.yaml
A few bits missed from https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/404 
> Missed a few bits on the switch to quay.io.

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.install
https://trello.com/c/MkSRxdWQ/1025-thumbnail-images
> Adding in missing file usage references to bring back images.

- config/sync/views.view.content.yml
https://trello.com/c/d1vzZdpJ/1150-prepare-to-release-new-homepage
This fixes an issue that prevented the new homepages from appearing on /admin/content
The fix has already been applied to production (via a direct config update).  So this PR is just to ensure that the changes are in the codebase, and do not get reverted on the next deployment.
> Fix for new homepages not showing up on content overview page.

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/jsonapi.settings.yml
- config/sync/views.view.front_page.yml
- docroot/sites/default/default.settings.php
Update to latest stable version of Drupal core.  Part of the reason for doing this is to get the latest version of the new text editor (ckeditor5).  But also for general house keeping.
The additional changes to config and settings file were automatically generated by the update (so need to be pushed into git to avoid having changes appearing later on).
> Updating drupal core to 9.4.3, with dependencies and new config.

- config/sync/core.entity_view_display.node.link.default.yml
- config/sync/core.entity_view_display.node.moj_pdf_item.default.yml
- config/sync/core.entity_view_display.node.moj_radio_item.default.yml
- config/sync/core.entity_view_display.node.moj_video_item.default.yml
- config/sync/core.entity_view_display.node.page.default.yml
- config/sync/core.entity_view_display.taxonomy_term.moj_categories.default.yml
- config/sync/core.entity_view_display.taxonomy_term.prisons.default.yml
- config/sync/core.entity_view_display.taxonomy_term.series.default.yml
- config/sync/core.entity_view_display.taxonomy_term.topics.default.yml
Fix for previous PR https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/427
Some config was not updated in the last PR.  This needs to be part of the codebase so that it doesn't keep appearing on deployments (Drupal will try to re-import the old config, but it will keep showing as out of sync so will attempt to do the same thing again and again).
> Updating config that came with the drupal core 9.4 update.

- docroot/sites/default/services.yml
> Adding request_uri to log output.

- docroot/modules/custom/jsonapi_filter_cache_tags/src/EventSubscriber/ResponseSubscriber.php
> Fix error on search query.

- docroot/modules/custom/jsonapi_filter_cache_tags/src/CacheTagsBuilder.php
- docroot/modules/custom/jsonapi_filter_cache_tags/tests/src/ExistingSite/JsonApiFilterCacheTagsTest.php
- docroot/modules/custom/prisoner_hub_sub_terms/tests/src/ExistingSite/PrisonerHubSubTermsTest.php
Adds tests related to previous PR https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/447
> Jsonapi cache tags tests

- composer.json
- composer.lock
- config/sync/editor.editor.basic_html.yml
- config/sync/editor.editor.full_html.yml
- docroot/sites/default/default.services.yml
Cli output:
```
➜  prisoner-content-hub-backend git:(feature/update-drupal-core-9.4.7) ✗ composer update drupal/core-recommended --with-dependencies
Gathering patches for root package.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 1 install, 34 updates, 0 removals
- Upgrading doctrine/collections (1.6.8 => 1.7.3)
- Locking doctrine/deprecations (v1.0.0)
- Upgrading doctrine/event-manager (1.1.1 => 1.1.2)
- Upgrading drupal/core (9.4.3 => 9.4.7)
- Upgrading drupal/core-recommended (9.4.3 => 9.4.7)
- Upgrading guzzlehttp/promises (1.5.1 => 1.5.2)
- Upgrading masterminds/html5 (2.7.5 => 2.7.6)
- …
```
> Upgrading Drupal core to 9.4.7

- composer.json
- composer.lock
- config/sync/editor.editor.basic_html.yml
- config/sync/editor.editor.full_html.yml
- docroot/sites/default/default.services.yml
Reverts ministryofjustice/prisoner-content-hub-backend#452
Required so that we can deploy hotfix https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/455
> Revert "Upgrading Drupal core to 9.4.7"

- composer.json
- composer.lock
- config/sync/editor.editor.basic_html.yml
- config/sync/editor.editor.full_html.yml
- docroot/sites/default/default.services.yml
Reverts ministryofjustice/prisoner-content-hub-backend#456
See original PR https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/452
This was merged in but had to be removed due to hotfix deployment.
> Revert "Revert "Upgrading Drupal core to 9.4.7""

- helm_deploy/prisoner-content-hub-backend/db-refresh.sh
- helm_deploy/prisoner-content-hub-backend/templates/db-refresh.yaml
- helm_deploy/prisoner-content-hub-backend/templates/drupal-post-install-hook.yaml
- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
Reverts ministryofjustice/prisoner-content-hub-backend#458
See original PR https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/439
This was merged in but had to be removed due to hotfix deployment.
> Revert "Revert "Database refresh""

- Makefile
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/prisoner_hub_taxonomy_sorting.module
Cleanup a couple of bits of code that were added for a deployment.
> Deployment cleanup

- helm_deploy/prisoner-content-hub-backend/db-backup.sh
- helm_deploy/prisoner-content-hub-backend/db-refresh.sh
- scripts/downloadDBFromBackup.sh
Speed up downloads and reduce storage of mysql backups.
> Use gzip on backups for faster downloads.

- helm_deploy/prisoner-content-hub-backend/s3-sync.sh
- helm_deploy/prisoner-content-hub-backend/templates/_envs.tpl
- helm_deploy/prisoner-content-hub-backend/templates/s3-sync.yaml
- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
https://trello.com/c/hBybalo3/1750-set-up-regular-job-to-duplicate-files-from-live-environment
Sets up a cronjob on development and staging environments to sync files from production. This is run every 24 hours, at 4:45am
This depends on PR https://github.com/ministryofjustice/cloud-platform-environments/pull/9431 being merged first.  So that the production bucket name is available as a secret in the development and staging environments.
> Automated s3 file syncing.

- helm_deploy/prisoner-content-hub-backend/templates/s3-sync.yaml
Fix issue with yaml added in previous PR https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/482
I thought I'd already tested the formatting, but turns out I didn't.
> Fix yaml formatting errors.

- helm_deploy/prisoner-content-hub-backend/db-backup.sh
Remove the `rm` line which was causing the job to fail.  The file had already been removed, due to using `aws mv` just before it.
> Fix db backup failing cronjob

- README.md
https://trello.com/c/P2REMJRO/1882-set-up-local-environment
Adding additional env variables that need to be set in order to use s3 on local environments.
> Update README with additional env variables for s3

- .circleci/config.yml
> Replace existing GitHub CircleCI key

- config/sync/views.view.category_map.yml
… access it.
https://trello.com/c/fQZgmmiD/1876-taxonomy-map-page-in-drupal-that-displays-full-taxonomy-hierarchy
Fix for incorrectly set permissions for the new "Category map" page (not yet deployed).
> Updating permissions to category map page

- config/sync/node.type.moj_pdf_item.yml
- config/sync/node.type.moj_radio_item.yml
- config/sync/node.type.moj_video_item.yml
- config/sync/node.type.page.yml
https://trello.com/c/KHyyRFTT/1905-drupal-edits-for-content-types-node
Updating the labels and descriptions for creating new content.
> Updating content type labels and descriptions.

- composer.lock
https://trello.com/c/HyR8Zcne/2060-update-to-drupal-95x
N/A
Update to installed Drupal core components to 9.5.5.
No
No
No
> ⬆️  update Drupal to 9.5.5.

- composer.lock
https://trello.com/c/zbawMtIX/18-book-blocks
N/A
Updates book_blocks module from 8.x-1.6 to 8.x-1.7
No
No
No
> ⬆️  update book_block module for D10 compatibility.

- composer.lock
- docroot/sites/default/default.settings.php
https://trello.com/c/wyCZcBDl/2121-upgrade-to-drupal-958
N/A
Upgrades Drupal to 9.5.8.
No.
No.
No.
> ⬆️  upgrade to Drupal 9.5.8

- composer.lock
https://trello.com/c/jYfqSIUR/967-update-to-drupal-959
N/A
Updates to composer lock to upgrade to Drupal 9.5.9.
No
No
No
> ⬆️  update to Drupal 9.5.9.

- helm_deploy/prisoner-content-hub-backend/values.development.yaml
https://trello.com/c/LgNVXNpA/2113-spike-investigate-how-to-move-prod-s3-bucket-from-ireland-to-london
N/A
We have created a second bucket in dev and sync'd it from the staging bucket. This PR changes the webservers to use this new bucket for Drupal so we can test it ahead of making the same changes in prod.
No
No
No
> 🔧  point development to new S3 bucket.

- helm_deploy/prisoner-content-hub-backend/values.production.yaml
N/A
We now have a new S3 bucket in prod in the same region as the web servers. This PR should start syncing the contents of the staging bucket to it.
No
No
No
> ✨  start syncing staging s3 to new prod bucket.

- composer.lock
https://trello.com/c/TKgHv13t/30-image-style-warmer
N/A
Upgrades the image_style_warmer module to latest version
No
No
No
> ⬆️  upgrade image_style_warmer to 8.x-1.2 to fix https://www.drupal.org/project/image_style_warmer/issues/3339995 and for Drupal 10 compatibility.

- composer.lock
https://trello.com/c/XsFfDcDY/28-form-state-empty
N/A
Updates form_state_empty module to the latest version for Drupal 10 compatibility.
No
This module https://www.drupal.org/project/form_state_empty is now maintained by us.
No
> ⬆️  update form_state_empty for Drupal 10 compatibility.

- composer.lock
https://trello.com/c/cSRzmpQ0/31-jsonapi-cross-bundles
N/A
Updates the jsonapi_cross_bundles module to 8.x-1.1.
No
No
No
> ⬆️  update jsonapi_cross_bundles for Drupal 10 compatibility.;

- composer.json
- composer.lock
- patches/3266585-support-other-entity-types-4.patch
No, but it is a precursor to https://trello.com/c/Ld4QiQXk/19-computed-breadcrumbs.
N/A
This module was being installed from an [issue](https://www.drupal.org/node/3243613) branch. This branch has been long merged so we should move back onto a supported branch so that we can move to the version supporting Drupal 10 as soon as it is available.
No
No
No
> 🔀  move computed_breadcrumbs module off 3243613 branch.

- composer.lock
https://trello.com/c/R5wXZvVQ/2173-update-to-drupal-9510
N/A
Updates Drupal to 9.5.10
No
> ⬆  update Drupal to 9.5.10.

- composer.lock
https://trello.com/c/1X8liGyE/33-jsonapi-page-limit
N/A
Update JSON:API Page Limit module to 8.x-1.1 version for Drupal 10 support.
Updates composer lock file to use the new version in build.
No
No
No
> ⬆️  Update JSON:API Page Limit to 8.x-1.1 for Drupal 10 support.

- composer.lock
https://trello.com/c/Bq4Y0KOy/26-flysystem
Increment version of flysystem from 2.0.0-beta1 to 2.1.0-rc4 to increase stability and add support for Drupal 10. 
Note this doesn't cover the flysystem_s3 module, which still does not support D10, but we can make this upgarde independently.
No
No
No
> ⬆️  Update Flysystem to 2.1.0-rc4 for D10 support.

- composer.json
- composer.lock
https://trello.com/c/IAyy86JJ/72-drupal-test-traits
https://trello.com/c/RIkOJ0U0/48-views-entity-form-field
https://trello.com/c/Z9lb5TZl/49-views-filters-populate
N/A
Updates 
* Drupal Test Traits
* Views Entity Form Fields
* Views Filters Populate
to their latest versions for D10 compatibility.
No
No
No
> Update multiple modules for Drupal 10 compatibility 

- config/sync/views.view.content.yml
- config/sync/views.view.taxonomy_overview.yml
https://trello.com/c/ROklWtZP/2177-update-all-contrib-modules
This is (intentionally) the second PR for this Trello card. It's a follow up to export the automated configuration changes made during that deployment to our config folder, so that import of the configuration in subsequent deployments does not revert those automated changes.
No.
This does not need to be deployed for it's own sake.
> 🔧  update views configuration following hook_update function executed when deploying updated contrib to prod.

- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
https://trello.com/c/xHH9DhMo/2178-update-analytics-ids-for-back-end
NA
It does exactly what the title of the Trello card says.
No.
No
No
> 📈  update analytics IDs so they are no longer shared with the front end application.

- docroot/sites/default/settings.php
- helm_deploy/prisoner-content-hub-backend/db-backup.sh
- helm_deploy/prisoner-content-hub-backend/db-refresh.sh
- helm_deploy/prisoner-content-hub-backend/s3-sync-temp.sh
- helm_deploy/prisoner-content-hub-backend/s3-sync.sh
- helm_deploy/prisoner-content-hub-backend/templates/_envs.tpl
- helm_deploy/prisoner-content-hub-backend/templates/cronjob.yaml
- helm_deploy/prisoner-content-hub-backend/templates/db-backup.yaml
- helm_deploy/prisoner-content-hub-backend/templates/db-refresh.yaml
- helm_deploy/prisoner-content-hub-backend/templates/deployment.yaml
- helm_deploy/prisoner-content-hub-backend/templates/drupal-cache-rebuild-cronjob.yaml
- helm_deploy/prisoner-content-hub-backend/templates/drupal-post-install-hook.yaml
- helm_deploy/prisoner-content-hub-backend/templates/drupal-scheduler-cronjob.yaml
- helm_deploy/prisoner-content-hub-backend/templates/s3-sync-temp.yaml
- helm_deploy/prisoner-content-hub-backend/templates/s3-sync.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
This reverts commit 0e87244a2cbffaba63739dc39bfee3d03add301c.
No
See INC2167313
Revert use of service roles for S3 access and return to access keys.
No
No
No
> Revert "Use service account for AWS IAM creds (#541)"

- composer.lock
> Does this issue have a JIRA ticket?
https://dsdmoj.atlassian.net/browse/LNP-273
N/A
Updates Drupal core and dependencies following the attached security advisory https://www.drupal.org/sa-core-2023-006
No
No
No
> LNP-273: ⬆️  update to Drupal 9.5.11.

- composer.json
- composer.lock
- patches/linkit-2877535-64.patch
https://dsdmoj.atlassian.net/browse/LNP-436
Check the Drupal admin update status report. That will indicate the CSV Serialization is running an unsupported version.
Update CSV Serialization to the supported 3.0.x branch, and applies all other available composer updates.
No
No
No - but note database updates will automatically apply. In a local environment these took a few seconds.
> LNP-436: update contrib modules & composer packages

- docroot/modules/custom/prisoner_hub_bulk_updater/prisoner_hub_bulk_updater.deploy.php
https://dsdmoj.atlassian.net/browse/LNP-563
Deploy current main HEAD to staging.
* Reduces the batch size from 100 to 10
* Logs exceptions
* Outputs all nids updated in each batch
to make it easier to identify where this is happening.
No
No
> LNP-563: 🔊  reduce batch size and add additional logging to red content update to troubleshoot issues on staging.

- .circleci/config.yml
- helm_deploy/prisoner-content-hub-backend/templates/s3-sync.yaml
https://dsdmoj.atlassian.net/browse/LNP-627
Go to sleep. When you wake up, the dev S3 sync will have failed overnight.
Explicitly add the service account name to the cron job definition.
No
No
No
> LNP-627: dev s3sync failing

- composer.lock
https://dsdmoj.atlassian.net/browse/LNP-554
Ups the version of aws/aws-sdk-php package to the latest.
No
No
No
> LNP-544: 🎶  update aws sdk php package.

- composer.json
- composer.lock
- config/sync/core.extension.yml
https://dsdmoj.atlassian.net/browse/LNP-630
N/A
Adds the https://www.drupal.org/project/uploaded_file_filename_randomizer contrib module to randomise uploaded file names.
No
No
No
> LNP-630: 🎉 uploaded files filename randomisation 

- LICENSE.txt
https://dsdmoj.atlassian.net/browse/LNP-285
N/A
Adds the standard LICENSE.txt file from https://github.com/ministryofjustice/template-repository/blob/main/LICENSE in line with the departmental repository standards.
No
No
No
> LNP-285: 📄  add LICENSE.TXT file in line with repository standards.

- config/sync/user.role.local_administrator.yml
https://dsdmoj.atlassian.net/browse/LNP-634
N/A
This PR removes permissions that should no longer belong to this role, and adds permissions that should.
No
No
No
> LNP-634: 🛂  Changes to Studio Administrator role.

- config/sync/field.field.node.link.field_moj_thumbnail_image.yml
- config/sync/field.field.node.moj_pdf_item.field_moj_thumbnail_image.yml
- config/sync/field.field.node.moj_radio_item.field_moj_thumbnail_image.yml
- config/sync/field.field.node.moj_video_item.field_moj_thumbnail_image.yml
- config/sync/field.field.node.page.field_moj_thumbnail_image.yml
- config/sync/field.field.taxonomy_term.moj_categories.field_moj_thumbnail_image.yml
- config/sync/field.field.taxonomy_term.series.field_moj_thumbnail_image.yml
- config/sync/field.field.taxonomy_term.topics.field_moj_thumbnail_image.yml
https://dsdmoj.atlassian.net/browse/LNP-640
Upload an image of 11000 by 7000 pixels when creating / editing content. Content will WSOD on subsequent edits.
Restricts uploaded images to max 1024x1024 resolution and 2MB is size.
No
No
No
> LNP-640: 🔧 restrict resolution and size of files uploaded to fields.

- config/sync/update.settings.yml
https://dsdmoj.atlassian.net/browse/LNP-652
NA
changed the email address. The configuration fetch url has been changed because the update configuration couldn't be saved with an invalid value of an empty string
NA
NA
NA
> LNP-652-update-email-notification-drupal

- composer.json
- composer.lock
No
No
Updates for Drupal contrib modules
No
No
No
> LNP-792-Added-updates-diff-maxlength-contribs

- Dockerfile
https://dsdmoj.atlassian.net/browse/LNP-284
N/A
Updates to the latest version of composer
No
No
No
> LNP-284: ⬆️  update composer to 2.7.7

- docroot/modules/custom/field_group_open_non_empty/field_group_open_non_empty.info.yml
- docroot/modules/custom/file_download_expires_fix/file_download_expires_fix.info.yml
- docroot/modules/custom/page_cache_persist/page_cache_persist.info.yml
- docroot/modules/custom/prisoner_hub_breadcrumbs/prisoner_hub_breadcrumbs.info.yml
- docroot/modules/custom/prisoner_hub_bulk_updater/prisoner_hub_bulk_updater.info.yml
- docroot/modules/custom/prisoner_hub_cms_help/prisoner_hub_cms_help.info.yml
- docroot/modules/custom/prisoner_hub_content_suggestions/prisoner_hub_content_suggestions.info.yml
- docroot/modules/custom/prisoner_hub_edit_only/prisoner_hub_edit_only.info.yml
- docroot/modules/custom/prisoner_hub_explore/prisoner_hub_explore.info.yml
- docroot/modules/custom/prisoner_hub_linkit_matcher/prisoner_hub_linkit_matcher.info.yml
- docroot/modules/custom/prisoner_hub_primary_nav/prisoner_hub_primary_nav.info.yml
- docroot/modules/custom/prisoner_hub_prison_access/prisoner_hub_prison_access.info.yml
- docroot/modules/custom/prisoner_hub_prison_access_cms/prisoner_hub_prison_access_cms.info.yml
- docroot/modules/custom/prisoner_hub_prison_context/prisoner_hub_prison_context.info.yml
- docroot/modules/custom/prisoner_hub_recently_added/prisoner_hub_recently_added.info.yml
- docroot/modules/custom/prisoner_hub_sub_terms/prisoner_hub_sub_terms.info.yml
- docroot/modules/custom/prisoner_hub_taxonomy_access/prisoner_hub_taxonomy_access.info.yml
- docroot/modules/custom/prisoner_hub_taxonomy_child_count/prisoner_hub_taxonomy_child_count.info.yml
- docroot/modules/custom/prisoner_hub_taxonomy_field_ux/prisoner_hub_taxonomy_field_ux.info.yml
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/prisoner_hub_taxonomy_sorting.info.yml
- docroot/modules/custom/text_editor_refresh_images/text_editor_refresh_images.info.yml
- docroot/themes/custom/prisconhub/prisconhub.info.yml
https://dsdmoj.atlassian.net/browse/LNP-885
N/A
Updates version constraints for all modules to remove D9 compatibility and add D11 compatibility.
No, but there's a screenshot of the compatibility report in the description of the Jira ticket.
No
No
> LNP-820: ⬆️  update version constraint for all custom modules and theme for Drupal 11 compatibility.

- composer.lock
https://dsdmoj.atlassian.net/browse/LNP-1023
N/A
Updates lock file to update admin_toolbar to 3.5.1.
No
No
No
> LNP-1023: ⬆️  update admin_toolbar to 3.5.1.

- .github/pull_request_template.md
https://dsdmoj.atlassian.net/browse/LNP-1053
N/A
Adds a checkbox to this very PR template to indicate cache testing has been performed.
No
No
This change does not require deployment.
> LNP-1053: 👷‍♂️ add checkbox to PR template for cache testing.

- composer.lock
https://dsdmoj.atlassian.net/browse/LNP-1071
N/A
Updates composer.lock file to update Drupal to 10.3.9
No
No
No
> LNP-1071: ⬆️  Drupal 10.3.9.

- composer.lock
- docroot/sites/default/default.settings.php
https://dsdmoj.atlassian.net/browse/LNP-1071
N/A
Updates core-recommended and dependencies to 10.3.9.
No
No
No
> LNP-1071: Drupal 10.3.9 follow up

- requests/front end requests.http
https://dsdmoj.atlassian.net/browse/LNP-1080
N/A
Adds two more http requests for testing calls to Drupal via jsonapi search API, for the search preview, and search page respectively.
No
No
No
> LNP-1080: 🔎  add search requests to http requests file.

- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
No
Add standard prometheus alerting
> Add prometheus alerting

- config/sync/views.view.content.yml
[LNP-1097](https://dsdmoj.atlassian.net/browse/LNP-1097)
N/A
Adds a filter to the Content View for language (English/Welsh).
No
No
No
[LNP-1097]: https://dsdmoj.atlassian.net/browse/LNP-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LNP-1097: 🏴󠁧󠁢󠁷󠁬󠁳󠁿   add translation language filter to content overview.

- composer.json
- composer.lock
- docroot/modules/custom/prisoner_hub_bulk_updater/prisoner_hub_bulk_updater.deploy.php
- docroot/modules/custom/prisoner_hub_edit_only/src/Controller/EntityViewOverride.php
- docroot/modules/custom/prisoner_hub_explore/src/Resource/Explore.php
- docroot/modules/custom/prisoner_hub_primary_nav/src/Resource/PrimaryNavResource.php
- docroot/modules/custom/prisoner_hub_prison_access/tests/src/ExistingSite/PrisonerHubPrisonAccessJsonApiTest.php
- docroot/modules/custom/prisoner_hub_prison_access/tests/src/ExistingSite/PrisonerHubQueryAccessJsonApiByBundleTest.php
- docroot/modules/custom/prisoner_hub_prison_access_cms/tests/src/ExistingSite/PrisonerHubPrisonAccessCmsTest.php
- docroot/modules/custom/prisoner_hub_prison_context/src/PathProcessorOutbound.php
- docroot/modules/custom/prisoner_hub_recently_added/src/Resource/RecentlyAdded.php
https://dsdmoj.atlassian.net/browse/LNP-1128
N/A
Changes the version constraint to ~10.3.9 and updates all drupal/core-* packages.
The change of version constraint is necessary as the current constraint will update us to 10.4.x, and we would need to do more testing for that.
No
No
No
> LNP-1128: ⬆️ 🔒  update to Drupal 10.3.13.

- Dockerfile
- README.md
- docker-compose.override.yml
- docker-compose.yml
No
N/A
The build instructions for local build have been wrong since I started work on this project. This PR
* fixes those instructions
* removes redundant VERSION setting from docker compose files that raises warnings
* updates the apcu version for PHP 8.4 compatibility
No
No
No
> Fix local docker build.

- config/sync/views.view.category_map.yml
- config/sync/views.view.content.yml
- config/sync/views.view.taxonomy_overview.yml
https://dsdmoj.atlassian.net/browse/LNP-1118
Look at any of the views listed in the JIRA ticket.
You will see multiples entries for the same piece of content/category/series etc,
Removes duplicates by filtering out excessive rows caused by cross joins now we have multiple languages.
No.
No.
> LNP-1118: duplicates in views following multilingual enabling

- composer.lock
https://dsdmoj.atlassian.net/browse/LNP-1139
N/A
Updates composer depencies to Drupal 10.3.14 versions.
No
No
No
> LNP-1139: ⬆️  🔒  update to Drupal 10.3.14.

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/LNP-1160
N/A
Update CircleCI orb to 11.
No
No
No
> Update CircleCI orb to 11.
