- Dockerfile
Running an interactive shell with user `1000` highlights that the user isn't known.
I went to create the user, but found the Drupal Docker image already has `www-data`, so this PR updates the `chown` and user setting to `www-data`.
> Use www-data user

- helm_deploy/prisoner-content-hub-backend/values.yaml
The changes in #6 need to be applied to the Kubernetes [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) as well as the Docker image. 
This PR aligns the Helm charts and Docker image by using the same UID/GID.
No changes need to be made to the Docker Compose setup
> Set Security Context to use www-data UID and GID

- .circleci/config.yml
The checkout was failing due to the Helm Orb not tidying up installation scripts, the checkout for the release has been changed to use an explicit path
> Fix checkout failing in release job

- Dockerfile
```
Step 9/17 : COPY flysystem/flysystem.* /var/www/html/modules/contrib/flysystem
When using COPY with more than one source file, the destination must be a directory and end with a /
```
> Docker COPY needed a trailing slash

- Dockerfile
- Install mediainfo
- Break apart apt-get commands, makes it easier to read what each is doing in the build
> Install mediainfo when creating docker image

- modules/custom/moj_video_item/moj_video_item.install
This PR changes the migration to move the underlying File entity rather than clone.
Reason for this PR is after an investigation in to files and usages in Drupal we noticed that we had duplicate references in the database to the same files on disk. This would have caused the following issues post-migration;
- Orphan File entities in the database
- Files on disk would be removed during a pre-delete hook on the File entity if we went to remove duplicate file entities (1)
(1) https://api.drupal.org/api/drupal/core%21modules%21file%21src%21Entity%21File.php/function/File%3A%3ApreDelete/8.7.x
> Update migration to move File entity reference

- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
Only the production S3 bucket exists in Ireland. All other resources live in the London AWS Region.
This PR make the helm config reflect that, with an override for prod S3.
> update S3 defaults to match Terraform

- .circleci/config.yml
- helm_deploy/prisoner-content-hub-backend/values.development.yaml
This PR is the CMS complement to https://github.com/ministryofjustice/prisoner-content-hub-frontend/pull/28:
- Adds a gated deployment in the development namespace.
Intent:
To allow us to trivially deploy into the development environment for any branch.
This will overwrite any existing deployment, so there's a couple of caveats:
- Development can enter a broken state by moving back and forth with backend releases. If/when this happens, we'll restore a known good copy of the database.
- There's only one active deployment, so this approach won't work well for pull requests, where we often have many. This can easily be solved for the frontend, but for Drupal it's a bit trickier to spin up ephemeral databases.
> Cloud Platform development preview build

- helm_deploy/prisoner-content-hub-backend/templates/ingress.yaml
- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
This PR 
- removes some duplicates config in the ingress which I missed
- defaults the ingress to enabled to simplify config (we enable TLS/ingress in all our CP environments)
> fix copy/pasta error and enable TLS by default

- helm_deploy/prisoner-content-hub-backend/values.production.yaml
Because Ryan didn't have enough coffee today
> 🐛 Using the production URL instead of a typo

- helm_deploy/prisoner-content-hub-backend/templates/NOTES.txt
- helm_deploy/prisoner-content-hub-backend/templates/_helpers.tpl
- helm_deploy/prisoner-content-hub-backend/templates/deployment.yaml
- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.local.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
Following on from #50, this PR:
- Updates the templates to use the `hosts` array, taking the first host in the list as its canonical host name
- Reorders the production values file so `manage.content-hub.prisoner.service.justice.gov.uk` gets picked first
- Removes the `hostName` variable from all backend helm templates
Intent
It's a bit confusing to have `hostName` and `hosts` in the values file, and can lead to drift. This PR makes sure we've got a single definition for the host names in Helm.
> Use hosts array for helm variables

- .circleci/config.yml
- helm_deploy/prisoner-content-hub-backend/readme.md
- helm_deploy/prisoner-content-hub-backend/secrets.example.yaml
- helm_deploy/prisoner-content-hub-backend/templates/cronjob.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
- Added Kubernetes cron Helm template
- Update values.yaml to include cron values
- Update secrets example
- Update circle CI deploy step
- Update circle CI contexts
- Update Helm Readme
**NOTE**
Drupal cron jobs will need to be disabled (set to Never) to ensure it is remotely managed by the Kubernetes cron in this PR
> Add Kubernetes cron for Drupal

- helm_deploy/prisoner-content-hub-backend/templates/cronjob.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
Pairing @davidthomas22 and @spikeheap, we fixed up the cron jobs, testing the `prisoner-content-hub-development` namespace.
This PR:
- Fixes a naming issue with the cron job that caused the deployment to fail
- Improves the name of the pods for clarity
- Adds a security context to run the `curl` container non-root
- Corrects the `curl` image version to the latest one
- Runs the cron job every hour. It was running every 3 hours, but there's no reason not to run it more frequently
> fixes to enable drupal cron jobs

- helm_deploy/prisoner-content-hub-backend/templates/deployment.yaml
In https://app.circleci.com/pipelines/github/ministryofjustice/prisoner-content-hub-backend/188/workflows/b964127a-d7c6-4351-9358-068e79fea19c/jobs/126 the build fails because a value is unquoted:
```
ReadString: expects " or n, but found 1, error found in #10 byte of ...|,"value":126}],"imag|..., bigger context ...|lue":"*******"},{"name":"SENTRY_RELEASE","value":126}
```
This probably shouldn't be merged until the current upload issue is resolved, so I'll just leave it here :)
> Resolve helm deployment failure 

- .circleci/config.yml
I don't think this is quite right. It needs to depend on `build_preview` or `build_production`, does this require two separate jobs?
> Deploy to dev for all branches

- composer.json
- composer.lock
- helm_deploy/prisoner-content-hub-backend/values.yaml
This PR adds the ability to schedule when a post will be published or unpublished, using the `drupal/scheduler` plugin. I spent an hour or so evaluating the plugin and testing it locally
We also update the cron trigger to run more frequently (every 5 minutes). Scheduled posts are evaluated each `cron` run, so a post scheduled for `10:00:01` would _actually_ be published at `10:05:00` when the next job runs.
Once this PR is merged we need to:
I had wanted to set configuration in `settings.php`, but the nested, dynamic nature of applying this to each content type made it prohibitively difficult. Given more time I'd like to get `drush` working so we could apply these changes programmatically.
Scheduled publishing, alongside the change in publishing workflow to make "Published" content …
> Scheduled publishing

- README.txt
- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
For https://trello.com/c/9w8hYZJQ/1380-add-annotation-to-ingress-controllers.
This PR updates the kubernetes ingress annotation following https://mojdt.slack.com/archives/CH6D099DF/p1598372708002900.
This only applies to non-production environments initially. Once we're ready to roll it out across the board we should probably refactor this to remove the environment-specific annotations into something like:
```
{{- $namespace_name := .Release.Namespace }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
... removed for brevity
{{- with .Values.ingress.annotations }}
annotations:
kubernetes.io/ingress.class: {{ $namespace_name }}
{{- toYaml . | nindent 4 }}
{{- end }}
```
> Use namespace-specific nginx for non-production environments

- README.txt
- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.staging.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
Reverts ministryofjustice/prisoner-content-hub-backend#73
Cloud Platform have abandoned the custom-ingress approach, so we can undo this change.
> Revert "Use namespace-specific nginx for non-production environments"

- modules/custom/moj_resources/config/install/rest.resource.category_featured_content_resource.yml
Tested locally by uninstalling MoJ Rersources and reinstalling and checking the available endpoints.
> Add missing config file for MoJ Resources module

- .circleci/config.yml
https://trello.com/c/zjaTxHxL/1824-kubernetes-deployments-failing
- Run a deploy to Development step on a preview branch
- Update Kubernetes Orb to `0.11.2` (latest)
- Update Helm Orb to `1.2.0` (latest)
N/A
N/A
A successful build and deploy in CircleCI should verify that the issue is fixed
> Update deployment orbs to latest

- helm_deploy/prisoner-content-hub-backend/templates/_helpers.tpl
- helm_deploy/prisoner-content-hub-backend/templates/deployment.yaml
- sites/default/settings.php
https://trello.com/c/Zu6RS41d/1774-trusted-host-settings-not-enabled-in-drupal
N/A
Trusted host is configured in Drupal, the trusted host pattern is generated at deploy-time in Helm
N/A
We would need to validate both browser and service-to-service level interactions with Drupal
N/A
> Add configuration to set Trusted Hosts

- Dockerfile
For https://trello.com/c/9G8edxdb/95-install-pecl-uploadprogress-library-in-drupal-docker-image
Drupal can show upload progress to users. It's not currently doing this because a PECL module (`uploadprogress`) is missing. This PR resolves that.
The [status page](https://manage.content-hub.prisoner.service.justice.gov.uk/admin/reports/status) shows us the module is missing:
With this fix (tested locally with Docker Compose):
It would be good to check this in staging once it's been merged
> Are there any …
> Include uploadprogress PECL module. 

- sites/default/settings.php
Nope, it's a tiny cleanup issue, with no user-facing effects.
The Drupal status report (https://manage.content-hub.prisoner.service.justice.gov.uk/admin/reports/status) points out that this is an unnecessary config option now:
This PR removes the redundant line from `settings.php`.
No 🙂
To review this you can pull the branch locally, start Drupal, and see that the site loads.
> 🧹 Remove unused setting from settings.php.

- modules/custom/custom_action_prison_tagging/config/install/system.action.node_prison_tag_action.yml
- modules/custom/custom_action_prison_tagging/config/schema/custom_action_prison_tagging.schema.yml
- modules/custom/custom_action_prison_tagging/custom_action_prison_tagging.info.yml
- modules/custom/custom_action_prison_tagging/src/Plugin/Action/NodePrisonTagAction.php
- Add custom action module
- Add install and scheme info
- Add a custom action to tag content will all prisons
https://trello.com/c/64dZUJsD/1852-spike-drupal-vbo
Adds a custom action to the content admin to tag content with all prisons. 
_Note it only tags content if there are no prisons currently checked._
An update to the content admin to allow the content to filtered by prison tags would add value b/c it would reduce the number of content …
> Add prison tagging action

- modules/custom/moj_resources/src/TermApiClass.php
https://trello.com/c/4loln70n/1874-term-api-error-with-empty-fields
There should be no more warnings for accessing array indices on null values for the Term API endpoint in Drupal
Add ternary operators to check for a value before accessing an array
> Add check for fields when accessing in the Term API endpoint

- modules/custom/moj_resources/src/SeriesContentApiClass.php
No, this is a small fix to an issue
- Go to a series landing page, where the series has no prison category
- The page will have no content
Moved the check for a Prison Category on a Series until after we check for a Prison
N/A
N/A
N/A
> Move check for Series prison categories to after prison check

- Dockerfile
- helm_deploy/prisoner-content-hub-backend/templates/drupal-post-install-hook.yaml
No this is a very small change that doesn't warrant a card.
Currently to run drush you need to type in vendor/bin/drush which is obviously way too long and causes hours/weeks/months of wasted time and effort.
This PR adds the composer bin directory to the $PATH.  Allowing drush to be run with just `drush` (and everything else in the vendor/bin directory).
> Add composer bin to path

- config/sync/core.date_format.medium.yml
- config/sync/core.date_format.short.yml
No this is a small issue that doesn't warrant a card.
On the CMS pain points session an issue highlighted were the incorrect date formats.  
Drupal comes with default date formats that are in the US format i.e. month first, then date.   This PR updates those to be the "normal" format i.e. what the rest of the world uses, date and then month.
This should have no impact on the frontend, as none of the endpoints use Drupal's date formats (instead setting the date format directly in php).
The only change will be where dates are displayed in the Drupal CMS.  E.g. the `/admin/content` page.
> Swtiching from US to normal date formats.

- config/sync/field.field.node.moj_pdf_item.field_moj_archived.yml
- config/sync/field.field.node.moj_radio_item.field_moj_archived.yml
- config/sync/field.field.node.moj_video_item.field_moj_archived.yml
- config/sync/field.storage.node.field_moj_archived.yml
- docroot/modules/custom/moj/moj.install
https://trello.com/c/nlWyTuqj/21-remove-unused-fields-in-drupal
This PR does a bit of "prep-work" in order to allow us to remove fields.
There are two things required in order to get the database into a clean state, so that we can remove fields without any errors.
The field_moj_archived will be added back in, it will be removed again on the next deployment.  But there will be a period where the field exists and will be seen in the CMS.
> 21 remove unused fields in drupal prep

- composer.json
- composer.lock
- config/sync/core.extension.yml
No this is a small change that doesn't warrant a card.
Install the admin_toolbar module, an _almost-essential_ module that gives you dropdown menus in Drupal.  Saving hours upon hours of clicking and getting lost in Drupal's endless configuration pages.
See https://www.drupal.org/project/admin_toolbar (200,000 sites reported installed).
Will quickly demo this to the content team before deploying to prod.
It won't have any effect for local content managers, as they don't have any options underneath each menu item (so they never see the dropdown).
> Installing admin_toolbar module, to make it easier to navigate the CMS.

- docroot/modules/custom/moj/moj.install
https://trello.com/c/nlWyTuqj/21-remove-unused-fields-in-drupal
A fix for a deployment error.  
Some tables were previously added that were causing errors when deleting fields.  But there were too many added.  These extra ones cause errors on deployment, so we need to remove them.
> Remove unused fields in drupal part 2 (fix deployment issue)

- config/sync/user.role.local_administrator.yml
https://trello.com/c/GTLzL2nt/16-allow-studio-admins-to-assign-roles-in-drupal
Add ability for studio managers to assign local content manager and studio manager role to any user account.
> Adding role delegations to studio manager role.

- composer.json
- composer.lock
- config/sync/core.entity_view_mode.node.diff.yml
- config/sync/core.extension.yml
- config/sync/diff.settings.yml
https://trello.com/c/HaoIPISn/35-add-support-for-displaying-changes-in-each-revision
Installs the Drupal diff module (https://www.drupal.org/project/diff) this supports showing the difference between revisions.
As we are not using Drupal to preview content (currently), I have disabled the option to diff on the preview (as it looks a bit broken).  The default diff option is now the "split fields" view.
> 35 add support for displaying changes in each revision

- docroot/modules/custom/moj_resources/src/SeriesContentApiClass.php
https://trello.com/c/ThDYVbQ1/46-add-ability-to-sort-series-by-oldest-first
This PR implements the new sorting methodology for our rest endpoints, which means that the sorting on series will be updated in the frontend.
The previous sorting function has been removed, and instead sorting is applied on the entity query itself (which is more performant, and will fix the issue where series with 40+ episodes have missing content).
The value of the `field_sort_by` (added in https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/190) is now used to determine the sorting method.
No automated tests have been added/updated for this change, (the previous unit tests for these rest endpoints no longer work, and we will be moving to JSON:API in the …
> 46 add ability to sort series by oldest first

- composer.json
- composer.lock
- config/sync/cer.corresponding_reference.landing_page_back_reference.yml
- config/sync/core.entity_form_display.taxonomy_term.moj_categories.default.yml
- config/sync/core.entity_view_display.taxonomy_term.moj_categories.default.yml
- config/sync/core.entity_view_display.taxonomy_term.tags.default.yml
- config/sync/core.extension.yml
- config/sync/field.field.taxonomy_term.moj_categories.field_legacy_landing_page.yml
- config/sync/field.field.taxonomy_term.moj_categories.field_moj_prisons.yml
- config/sync/field.field.taxonomy_term.moj_categories.field_prison_categories.yml
- config/sync/field.field.taxonomy_term.tags.field_moj_prisons.yml
- config/sync/field.field.taxonomy_term.tags.field_prison_categories.yml
- config/sync/field.storage.taxonomy_term.field_legacy_landing_page.yml
- config/sync/field.storage.taxonomy_term.field_moj_prisons.yml
- docroot/modules/custom/prisoner_hub_entity_access/prisoner_hub_entity_access.services.yml
- docroot/modules/custom/prisoner_hub_entity_access/src/EventSubscriber/QueryAccessSubscriber.php
- docroot/modules/custom/prisoner_hub_prison_context/prisoner_hub_prison_context.services.yml
- docroot/modules/custom/prisoner_hub_prison_context/src/Routing/RouteSubscriber.php
- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.deploy.php
- docroot/sites/default/services.yml
https://trello.com/c/X0y3aNeI/113-implement-prison-category-rule-on-topics-page
This PR replaces https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/200
Introduces a new "cross-bundle" jsonapi resource /jsonapi/taxonomy_term (this can also be used on other entity types, e.g. `/jsonapi/node`)
This will also be available when using the prison in the url. E.g.
/jsonapi/prison/berwyn/taxonomy_term
As part of converting the /topics page to JSON:API, I've started the process of removing the landing_page content type (it won't be removed just yet, but the /topics JSON:API response will only return the taxonomy terms, and not the landing page node type).
To allow …
> 113 implement prison category rule on topics page 3

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.install
https://trello.com/c/5eUjIA5M/128-create-additional-prisons-in-drupal
As part of adding the new prisons into Drupal, we discovered that our prison categories in Drupal, don't quite match up with how these in real life.
We currently have a `Youth female` and an `Adult female`, but these types of prisons don't exist, you only have a `Women's` prison.
So to fix this, we will remove the `Youth female` taxonomy, and rename `Adult male` to `Women's`.  (This can be done directly on the production CMS).
This PR adds an update hook that takes all the content tagged with `Youth female` and updates it to:
1) Remove the reference to `Youth female`
2) Ensure it has a reference to `Adult female`
> Remove tags to youth female category.

- composer.json
- composer.lock
- patches/drupal-1149078-drupal-states_multiselect-104-drupal86.patch
- patches/drupal-3036593-118.patch
- patches/jsonapi_page_limit-add-option-to-set-global-limit-2.patch
No this is a small change that doesn't require a card.
Patches have been added that download directly from drupal.org and gitlab.com, these have been moved to local files.  This avoids a dependency in our builds on external services being available.  And also reduces the risks of supply-chain (package manager attacks).  Although files hosted on drupal.org should be permanent (i.e. once uploaded they can't be edited or removed), relying on this functionality is a security risk.
> Moving patches to local files

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/views.settings.yml
- config/sync/views.view.content.yml
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/prisoner_hub_taxonomy_sorting.module
- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.install
- patches/3173822-views_ef_fieldset-operator_issue-3.patch
https://trello.com/c/pXhgMj2C/141-assign-content-for-lindholme
To update the content for Lindholme and to avoid a timeout on the deployment, it was decided that we would use the bulk content update tool in the CMS.
This card adds a filter for prisons to the content overview page, allowing us to select all content tagged with Berywn *and* Wayland.  To allow the *and*, the "operator" had to be exposed.  As I did this, the layout of the filters broke, so I grouped everything into different sections.
I also added a filter for prison categories, and removed filters for language and "promoted to frontpage" (neither are in use).
https://user-images.githubusercontent.com/436483/119125484-b94a1e80-ba29-11eb-9399-b1764958a032.mov
> Is there any additional …
> 141 assign content for lindholme

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.install
https://trello.com/c/TQHhdb4i/151-unable-to-edit-certain-videos-in-drupal
This PR adds an update hook to re-instate the missing entries to the `file_usage` table.
We need to keep monitoring the database to see whether these entries come back, as it's not clear how they went missing in the first place.
> Fix unable to edit certain videos.

- composer.json
- composer.lock
Nope, it's a small change.
Bump Drupal version number up to 8.9.16, to include security fix for ckeditor.
We _should_ not be particularly vulnerable, as ckeditor is only used by people with a CMS account.
When updating Drupal core, I noticed that a contrib module `views_ef_fieldset` that was recently added, was applying a patch to drupal core.  This was being downloaded directly from drupal.org.
Since https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/206 we made a decision to only patch from local files.  
The patch from the module did not add any functionality, and was only used for the modules internal testing.  So it has been removed (by placing it in `patches-ignore`).
> Update drupal core 8.9.16

- composer.json
- composer.lock
- docroot/sites/default/settings.php
- patches/flysystem_s3_cors_upload-2770263-60.patch
https://trello.com/c/lT8SSUoL/152-spike-plug-in-for-video-and-audio-percentage-upload
File upload progress is apparently already a feature of the `flysystem_s3` module, but CORS has to be enabled on the S3 bucket.  Once it has been enabled, and the `CORS` setting set to `TRUE`, it should all magically work.
CORS has been added to the dev s3 bucket in https://github.com/ministryofjustice/cloud-platform-environments/pull/4854
CORS config needs to be added to MoJ hosting platform. These are done in three separate PRs:
- Dev (merged): https://github.com/ministryofjustice/cloud-platform-environments/pull/4854
- Staging (merged): https://github.com/ministryofjustice/cloud-platform-environments/pull/4863
- Production (reviewed but not yet merged): …
> 152 plug in for video and audio percentage upload

- config/sync/core.entity_form_display.node.featured_articles.default.yml
- config/sync/core.entity_form_display.node.landing_page.default.yml
- config/sync/core.entity_form_display.node.moj_pdf_item.default.yml
- config/sync/core.entity_form_display.node.moj_video_item.default.yml
- config/sync/core.entity_form_display.node.page.default.yml
- config/sync/core.entity_form_display.taxonomy_term.tags.default.yml
Previous (deployed) card https://trello.com/c/IpnUaB9o/950-improve-field-description-for-prison-and-prison-category-fields
The prison category field should be before the prison field, but was the wrong way round for several content types, this PR fixes that.
n/a
> Prison categories should be shown before the prison field.

- config/sync/user.role.authenticated.yml
There was a previous card https://trello.com/c/lT8SSUoL/966-enable-video-and-audio-upload-progress which was deployed to prod.  Unfortunately a setting was missed so that it wasn't actually enabled for studio admins or local comms manager accounts.  This PR adds in the setting.
Update permissions so that all authenticated users can use the CORS upload functionality. 
This should also hopefully fix Paul's issue uploading videos in Cookhamwood:
https://mojdt.slack.com/archives/C02097M28D9/p1623403471004900
none
> Enabling CORS upload progress for all logged in Drupal roles

- config/sync/user.role.authenticated.yml
Reverts ministryofjustice/prisoner-content-hub-backend#213
There's an issue with the CORS upload functionality, preventing files from being uploaded.
The change in this PR already been made on production (via the UI), this PR means the change does not get reverted on the next deployment.
> Revert "Enabling CORS upload progress for all logged in Drupal roles"

- docroot/sites/default/settings.php
https://trello.com/c/aGdfaKK5/165-do-we-have-an-login-change-audit-log
Failed login attempts are already logged (e.g. see https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/doc/89ddb820-d648-11ea-a3d9-7f47a73dbcba/kubernetes_cluster-2021.07.14?id=4UgGpHoBFuiXLfuCgzEZ&_g=(refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))
However, the IP address recorded is that from the load balancer, and not the original users IP.
This PR adds Drupal's reverse proxy support, to determine the original IP.
na
> 165 set originating IP address for betting logging

- composer.json
- composer.lock
Bumps Drupal core version to 9.1.11 to include security fix https://www.drupal.org/sa-core-2021-004
We are unlikely to be vulnerable to the security issue, as we do not have any custom or contributed code using the Archive_Tar library.  But we should update anyway to be sure.
na
> Updating to drupal core 9.1.11 to include security fix

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.deploy.php
Fix relating to previous PR As these could be linked through somewhere on the site currently.
Previously unpublished nodes were not given paths.  As we know that we have some unpublished content appearing on the site, we need to make sure they also have a path, so that the `router/translate-path` request can find it.
> Create paths for all nodes, including unpublished.

- docroot/modules/custom/prisoner_hub_prison_context/prisoner_hub_prison_context.services.yml
- docroot/modules/custom/prisoner_hub_prison_context/src/PathProcessorOutbound.php
- docroot/modules/custom/prisoner_hub_prison_context/src/Routing/RouteSubscriber.php
https://trello.com/c/fh1sP4L6/233-switch-to-jsonapi-for-basic-pages
This is a follow-on PR from https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/230, implementing option **a** from the **Considerations** section.
This PR modifies the decoupled router path, so that we can use the current prison.  This will also be returned in the jsonapi urls in the response.
Example:
> 233 modify decoupled router path

- docroot/modules/custom/moj_resources/src/Utils.php
This is a fix for the issue reported in https://trello.com/c/KZOMMSmY/226-check-content-is-appropriate-for-hmp-lindholme-launch-friday-20-august
Found there is a hard-coded list of prison ID's in the Drupal code.  If an ID is not part of the list (which Lindholme isn't), then it skips the check for the prison, and returns all results (for all prisons).
This PR removes this check, so that any prison ID is passed onto the query.  The difference means that
a) We don't need to manage this list of prison IDs (which we will be removing anyway once we switch to JSON:API)
b) If an invalid prison id is used, you get back no content.
We don't have to worry about malicious use of the prison id query parameter, as this will be sanitised by Drupal's entity query system.
> Fix for Lindholme not receiving the correct content

- composer.json
- composer.lock
- patches/drupal-3228329-files-uploaded-through-text-editor-cache-dependency-2.patch
This fix is related to https://trello.com/c/fh1sP4L6/233-switch-to-jsonapi-for-basic-pages
This fixes the issue of files uploaded through the text editor getting expired urls.
The cache metadata of the file was not being properly passed onto the containing content.  So whilst we are setting a max-age for the file based on the url signature expiration, this was not being used when the file was uploaded inside a text editor field.
This is a bug in Drupal, I opened an issue for this: https://www.drupal.org/project/drupal/issues/3228329
As this is a patch to Drupal core, we should monitor the above issue to see whether this is an acceptable solution or not.
It may also be worth writing tests for this, to ensure that the fix gets committed back in.
> Fix issue where image urls inside the text editor were expiring.

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.profile
https://trello.com/c/VWPKV7Rs/212-stop-email-error-messages-appearing-in-the-logs
This PR essentially disables all emails Drupal tries to send, from being sent.
As we do not have a mailing service, all outgoing emails result in an error in the logs.  As this happens fairly frequently (e.g. on every cron run), it causes a large amount of unnecessary log entries.
Emails are typically sent out on cron runs (to notify the "site owner" or updates) and when a user tries to reset their password.
Whilst this PR disables the email from being sent, a user can still access the "Reset my password" page, fill out their email, and submit the form.  Nothing is shown to the user to let them know this process doesn't work.
We did discuss removing this in …
> Disable all outgoing emails, to keep the logs a little bit tidier.

- config/sync/field.storage.node.field_moj_series.yml
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/prisoner_hub_taxonomy_sorting.module
- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.install
https://trello.com/c/I3GkyBuT/113-only-allow-content-to-be-linked-to-one-series
Updates the `field_moj_series` to accept just one item.
Includes an update hook to set all existing content with more than one series to just have the first series they were associated with.
> Limiting series field to one item.

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/maintenance_exempt.settings.yml
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/prisoner_hub_taxonomy_sorting.deploy.php
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/prisoner_hub_taxonomy_sorting.install
The deployments on main branch are currently failing, the k8ns fails and the pods are restarted.
Because the Drupal site gets put into maintenance mode during the deployment, and this disables the health check.
This PR does two things:
1) Installs the maintenance_exempt module, and configures it to allow the health check, JSONAPI, and REST api urls to still be accessible when the site is in maintenance mode.
2) Moves the problematic update hook to a deploy hook, which does not operate in maintenance mode.
> Fix deployment health check issue

- config/sync/views.view.series_taxonomy_term_content_sorting.yml
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/src/Controller/SeriesPageController.php
Related to https://trello.com/c/EyX2RFzY/254-switch-to-jsonapi-for-series-pages
Now that https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/238 has been merged in, this PR updates the "Change episode order" page to use the new field for sorting.  
The "Change episode order" page appears as a tab when editing a series or secondary tag. 
Note that there should be no visual change to the page, it should behave in exactly the same way as before.  We are just simplifying how the sorting is done, and aligning it with how sorting will be achieved through JSON:API.
> Update change episode order page 

- config/sync/field.field.node.moj_pdf_item.field_release_date.yml
- config/sync/field.field.node.moj_radio_item.field_release_date.yml
- config/sync/field.field.node.moj_video_item.field_release_date.yml
- config/sync/field.field.node.page.field_release_date.yml
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/prisoner_hub_taxonomy_sorting.module
No, this is an issue reported on Slack:
https://mojdt.slack.com/archives/C9EKLJ1QE/p1631176829002200
The last deployment introduced a change where when content is saved, a sort value is calculated.  This value is based on the season+episode number fields *or* the release date field (depending on what series had been selected).
The error was caused when the value was empty, and the content was first being added.
This is because of a warning message printed out, which included a link to the content.  At this point, there was no url for the content, so there was a PHP error.
Also, to avoid user submitting empty values, I've made the season+episode number fields required.
The release date field I couldn't make required (due to an issue in drupal core, …
> Fix issue with missing sort values

- composer.json
- composer.lock
- patches/flysystem_s3-add-delete-logging-for-debugging.patch
Context
Does this issue have a Trello card?
https://trello.com/c/ZVSfPcz6/89-fix-the-mysterious-missing-file-issue
Intent
This PR adds logging to when files are deleted from S3. This logging will only apply to files that are deleted through Drupal.
Previously it was thought that files were never deleted in Drupal. But since enabling S3 file logging ministryofjustice/cloud-platform-environments#5497, we have discovered that Drupal is sometimes deletes files. We disabled logging ministryofjustice/cloud-platform-environments#5551 as it was no longer required, and will use the logging provided by this PR to further investigate the issue.
Considerations
Is there any additional information that would help when reviewing this PR?
Are there any steps required when merging/deploying this PR? …
> Add delete file logging

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.deploy.php
https://trello.com/c/EyX2RFzY/112-switch-to-jsonapi-for-series-pages
This PR is needed before we switch over JSON:API for series https://github.com/ministryofjustice/prisoner-content-hub-frontend/pull/361.  As part of the change, we will switch to using the description field for the intro text at the top of the page.  This will keep it inline with how all other content/taxonomy works on the Hub.
Currently there is a summary field, which is being used.  This PR copies over all the values from summary to description.
After both this PR and https://github.com/ministryofjustice/prisoner-content-hub-frontend/pull/361 have been deployed, we should then remove the previous field. This is in a separate PR …
> Copy series summary to description

- docroot/sites/default/services.yml
https://trello.com/c/xL7P4r7Z/274-fix-drupal-and-sentry-integration
This should hopefully fix the Sentry integration, there appears to be an issue integrating with the monologger module (which was enabled to allow logging in cloud platform).
If this doesn't work, the next step would be to update the sentry module and client.
> Adding sentry as an output for monologger.

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.deploy.php
https://trello.com/c/Ar7YBRus/208-switch-to-jsonapi-for-category-landing-pages
Cherry picking c089de8eea178c68cd274e9080f845b4ddac0ed5 from https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/266 (as we don't want to remove landing pages just yet, can do that as part of a "cleanup" release).
> Update landing page urls embedded in description fields.

- composer.json
- composer.lock
- config/sync/core.entity_form_display.node.page.default.yml
- config/sync/core.extension.yml
- docroot/modules/custom/prisoner_hub_featured_content/js/prisoner-hub-featured-content.js
- docroot/modules/custom/prisoner_hub_featured_content/tests/src/ExistingSiteJavascript/FeaturedContentFieldsFormTest.php
- docroot/modules/custom/prisoner_hub_taxonomy_field_ux/prisoner_hub_taxonomy_field_ux.info.yml
- docroot/modules/custom/prisoner_hub_taxonomy_field_ux/src/EntityFormStates.php
No, this was an issue reported by Jo today on Slack.
A bug was discovered where the series sorting fields (i.e. the season+episode number or release date fields) were not shown when selecting a series.  This only occurred if an image had been uploaded first onto the form (for some reason this messed up the visible/invisible states).
This PR fixes the issue by setting the correct form states, that work after an image has been uploaded.
> Fix missing series field issue

- config/sync/field.field.node.moj_pdf_item.field_moj_top_level_categories.yml
- config/sync/field.field.node.moj_video_item.field_moj_top_level_categories.yml
This is related to https://trello.com/c/hCm7yE4Q/209-switch-to-jsonapi-for-in-this-section-sidebar-component
Discovered during testing the release that the category field was still required on two content types, this would have prevented content from being saved/updated that was part of a series (as the category field would be hidden).
The fields have already been updated on live, this PR adds this into config so it doesn't get reverted on the next release.
> Make category fields optional

- config/sync/core.entity_form_display.node.page.default.yml
https://trello.com/c/oo5RlgEP/417-move-standfirst-in-drupal-to-top-of-page
This update has already been made on production, this PR adds the config into code, so that we don't revert the change on the next deployment.
> Moving standfirst field to top of content edit form.

- docroot/modules/custom/prisoner_hub_featured_content/js/prisoner-hub-featured-content.js
https://trello.com/c/kkzyF5JE/102-allow-greater-control-of-featured-content-on-category-pages
This is a small optimisation, that fixes a bug where the category is still shown after `field_not_in_series` is switched.
https://user-images.githubusercontent.com/436483/140506778-c95095c6-afb3-4532-b9e5-32cad93017d8.mov
> Hide the featured category when field_not_in_series is switched

- composer.json
- composer.lock
- patches/flysystem_s3-3248956-disable-other-fields-when-uploading.patch
https://trello.com/c/ZVSfPcz6/89-fix-the-mysterious-missing-file-issue
and
https://trello.com/c/ididuzch/227-prevent-user-from-saving-content-before-a-file-has-finished-uploading
Currently multiple files can be uploaded simultaneously, i.e. a video and a thumbnail can be uploaded at the same time.
When this happens, the first file that finishes uploading to S3, has to actually wait for the second file to upload, and this file ends up getting sent directly to Drupal (in addition to S3), which is totally unnecessary.   This issue is described here: https://www.drupal.org/project/flysystem_s3/issues/3248956
Whilst this doesn't actually cause any errors, if both files are uploaded successfully, it does slow things down.  It also means that if one file …
> Disable other file fields and submit buttons when uploading.

- config/sync/views.view.content.yml
This PR is based on https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/300
This updates the content overview page /admin/content with the new prison field.
As prisons and prison categories are now combined, they can be filtered and shown in just one field.
New filter, with hierarchy 
New field in table, showing both prison categories and prisons.
There are further improvements to this page planned in https://trello.com/c/cG3gVH3O/305-improvements-to-the-content-overview-page
Which will include updating the field to use checkboxes, instead of a dropdown.  For now we are just using what functionality comes with Drupal as standard to do this filter.
> Update content overview page with new prison field.

- config/sync/core.extension.yml
https://trello.com/c/Wa7f4PAU/495-update-drupal-to-latest-version
In https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/316 a bunch of config was updated (via the Drupal core update process), and this accidentally wiped a recent change brought in https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/312
This PR adds back in the change.
> Re-enabling module which got removed by Drupal core config update merge.

- helm_deploy/prisoner-content-hub-backend/templates/drupal-cache-rebuild-cronjob.yaml
https://trello.com/c/wSOaJS7g/515-fix-broken-images-with-cron
This PR adds a new cronjob, that runs `drush cache-rebuild` everyday at 3:01AM.
Why 3:01AM?  Because s3 signatures are set to expire at 3:00AM every day, so by running this at 3:01 we ensure that any newly generated urls will be for the _next_ day at 3:00AM.
> Adding cronjon to rebuild cache at 3:01AM every day.

- docroot/modules/custom/prisoner_hub_edit_only/prisoner_hub_edit_only.module
- docroot/modules/custom/prisoner_hub_edit_only/src/Controller/EntityViewOverride.php
- docroot/modules/custom/prisoner_hub_edit_only/tests/ExistingSite/EditOnlyTest.php
https://trello.com/c/atLA4c1V/539-help-pages-can-no-longer-be-viewed-in-drupal
This fixes a bug introduced by https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/312
The changes from this PR redirected all "View" pages in Drupal to the "Edit" page.  This included help pages, which we _do_ want to view in Drupal.
This PR adds support for excluding help pages (and other content types in the future) from the redirect.  New content types will automatically be redirected, so much be specifically added to the EntityViewOverride::$excludedContentTypes array.
> Fix help pages not being viewable in Drupal.

- config/sync/core.entity_form_display.node.featured_articles.default.yml
- config/sync/core.entity_view_display.node.featured_articles.default.yml
- config/sync/core.entity_view_display.node.featured_articles.teaser.yml
- config/sync/field.field.node.featured_articles.field_featured_tile_large.yml
- config/sync/field.field.node.featured_articles.field_featured_tile_small.yml
- config/sync/field.storage.node.field_featured_tile_large.yml
- config/sync/field.storage.node.field_featured_tile_small.yml
- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.deploy.php
https://trello.com/c/ouqhJ3R0/532-allow-homepage-tiles-to-link-to-series
This PR adds two new fields to the homepage (featured_articles) content type.  These are exactly the same as the existing fields, but are dynamic entity reference fields (as opposed to standard entity reference fields).  This allows them to link to other entity types.  In this PR, we have enabled taxonomy terms and series.
The values from the previous two fields are copied across, and the previous two fields are then hidden from the form display.  So any content updates from this point will be to the new fields.
The two new fields are called:
- field_featured_tile_large (previously field_moj_featured_tile_large)
- field_featured_tile_small (previously …
> Allow homepage tiles to link to series

- composer.json
- patches/jsonapi_page_limit_fix_pager_links.patch
https://trello.com/c/w9ODRIv3/211-paginate-secondary-tags-and-series-pages
This fixes an issue with the  [jsonapi_page_limit](https://www.drupal.org/project/jsonapi_page_limit) module we are using.  The module would override the `offset` so any pager link from the second page onewards would be incorrect.
The [jsonapi_page_limit](https://www.drupal.org/project/jsonapi_page_limit) is a small module that allows the default limit of 50 items to be increased (this is the limit set by Drupal core).  
At the moment we need this for the "In this section" sidebar component (as some categories have over 50 series).
Whilst the module is very basic in what it does, it's not really properly maintained.  The reason for this is that the functionality for increasing …
> Fixing incorrect jsonapi pager links.

- composer.json
- patches/drupal-3254553-fileurlgenerator-external-files-20.patch
- patches/drupal-3254553-fileurlgenerator-external-files-7.patch
- patches/drupal-3254727-file-links-with-query-parameters-2.patch
https://trello.com/c/pQ2b2byz/538-unable-to-view-audio-video-files-in-drupal
This PR adds two new patches to Drupal core to fix the issues introduced by the 9.3.0 update.  These fix the broken file urls inside Drupal.
For more info on the patches, see:
- https://www.drupal.org/project/drupal/issues/3254553
- https://www.drupal.org/project/drupal/issues/3254727
Documentation about this has been added to https://dsdmoj.atlassian.net/wiki/spaces/HUB/pages/3760291937/Drupal+and+S3#Drupal-core-update-9.3.0
> Adding patches to drupal core to fix broken file viewing issue.

- composer.json
- patches/elasticsearch_connector-flattenkeys-2952301-15.patch
https://sentry.io/organizations/ministryofjustice/issues/2862238065/
There is a bug with the elasticsearch_connector module when a word is searched for beginning with `-`.  E.g. `-something`.
This causes a PHP fatal error.  This PR adds a patch to fix this from https://www.drupal.org/project/elasticsearch_connector/issues/2952301
> Fixing php error when searching for words beginning with hyphens.

- config/sync/core.extension.yml
- docroot/modules/custom/page_cache_persist/README.md
- docroot/modules/custom/page_cache_persist/page_cache_persist.info.yml
- docroot/modules/custom/page_cache_persist/page_cache_persist.services.yml
- docroot/modules/custom/page_cache_persist/src/Cache/PageCachePersist.php
- docroot/modules/custom/page_cache_persist/src/Commands/PageCachePersistCommands.php
- docroot/modules/custom/page_cache_persist/src/EventSubscriber/CacheRouterRebuildSubscriber.php
- docroot/modules/custom/page_cache_persist/tests/src/PageCachePersistTest.php
https://trello.com/c/LQ6xpxSV/581-fix-performance-issues-during-drupal-deployments
This PR adds a new Drupal module that overrides the cache.page service, to prevent the page cache from being cleared when `drush cache:rebuild` is called.
This will mean the page cache is retained during deployments, fixing performance issues that effect the site immediately after a deployment (where Drupal has to rebuild the page cache for every request).
There is an alternative method for implicitly clearing the page cache.
```
drush cache:force-clear-page
```
Details of this will be added to https://dsdmoj.atlassian.net/wiki/spaces/HUB/pages/3757342835/Caching+in+Drupal
When Drupal clears out the cache, it also rebuilds the router, picking up any new or modified …
> Prevent page cache from being cleared during deployments.

- docroot/modules/custom/prisoner_hub_edit_only/prisoner_hub_edit_only.module
- docroot/modules/custom/prisoner_hub_edit_only/tests/ExistingSite/EditOnlyTest.php
https://trello.com/c/e6MQjFUu/587-fix-this-content-has-been-modified-by-another-user-issue
Previously, Drupal would redirect the user to the "View" page after saving content.  Since we disabled this page, the user is shown the same edit form they were previously on.
When content is saved, Drupal checks to see if a more recent change was made to the same content.  If so, it assumes that there is a more recent modification, and the current one is stale.  Showing the user the "The content has been modified by another user" error.
The date it checks from is when the edit form was originally loaded, in our case this was when the form was first loaded, i.e. the value wasn't being updated after the edit page is refreshed (when the content is saved). 
This …
> Fixing "content has been modified by another user" error when re-saving content

- config/sync/core.entity_form_display.user.user.default.yml
- config/sync/core.entity_view_display.user.user.compact.yml
- config/sync/core.entity_view_display.user.user.default.yml
- config/sync/field.field.user.user.field_user_prisons.yml
- config/sync/field.storage.user.field_user_prisons.yml
https://trello.com/c/mtYpgoDF/575-allow-any-user-from-a-prison-to-edit-content-published-by-anyone-from-that-prison
This PR adds a new `field_user_prisons` to the user entity type, this will allow us to start associating users with prisons. 
We can then complete the changes from https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/335
> Add a prison field to the user.

- docroot/modules/custom/prisoner_hub_content_suggestions/src/Resource/ContentSuggestions.php
https://trello.com/c/nbxMo7d4/635-you-might-like-component-is-bugged
The you might like component was returning inconsistent results, with sometimes less than 4 items being returned inside `data`, and items appearing as `omitted`.
The issue was caused by the fact that unpublished items were not being excluded from the query.  This meant they got removed from the JSON:API response _after_ the query had run.  Resulting in a reduced total number of items being returned.
This PR adds the publishing status as a condition to the query, so that the 4 items returned by the query will always be accessible and not get excluded.
> Are there any steps required when merging/deploying …
> Fix content suggestions not returning consistent results.

- patches/stream_util-pr3-more-robust-version-of-getsize.patch
https://trello.com/c/48w0up7I/661-fix-image-upload-button-not-working-in-text-editor
This PR fixes an issue introduced by the changes in https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/340
As we are now streaming CSS/JS through Drupal (from S3), there was an issue with one of the PHP libraries being used, which was using a patch that didn't support streaming through PHP in this way.
The issue and fix is better described here:
https://www.drupal.org/project/drupal/issues/3179014#comment-14410242
> Fix issue with broken PHP streams that results in empty CSS/JS.

- config/sync/core.entity_form_display.taxonomy_term.moj_categories.default.yml
- config/sync/core.entity_view_display.taxonomy_term.moj_categories.default.yml
- config/sync/field.field.taxonomy_term.moj_categories.field_featured_image.yml
Add the image field (same as on series) to the category Taxonomy.  So that CMS users can upload images for sub-categories.
> Adding image field to category taxonomy.

- composer.json
- composer.lock
- config/sync/computed_breadcrumbs.settings.yml
- config/sync/core.entity_view_display.node.external_link.default.yml
- config/sync/core.entity_view_display.node.featured_articles.default.yml
- config/sync/core.entity_view_display.node.moj_pdf_item.default.yml
- config/sync/core.entity_view_display.node.moj_radio_item.default.yml
- config/sync/core.entity_view_display.node.moj_video_item.default.yml
- config/sync/core.entity_view_display.node.page.default.yml
- config/sync/core.entity_view_display.taxonomy_term.moj_categories.default.yml
- config/sync/core.entity_view_display.taxonomy_term.prisons.default.yml
- config/sync/core.entity_view_display.taxonomy_term.series.default.yml
- config/sync/core.entity_view_display.taxonomy_term.tags.default.yml
- config/sync/core.extension.yml
- docroot/modules/custom/prisoner_hub_breadcrumbs/README.md
- docroot/modules/custom/prisoner_hub_breadcrumbs/prisoner_hub_breadcrumbs.info.yml
- docroot/modules/custom/prisoner_hub_breadcrumbs/prisoner_hub_breadcrumbs.services.yml
- docroot/modules/custom/prisoner_hub_breadcrumbs/src/NodeBreadcrumbBuilder.php
- docroot/modules/custom/prisoner_hub_breadcrumbs/src/TermBreadcrumbBuilder.php
- docroot/modules/custom/prisoner_hub_breadcrumbs/tests/src/ExistingSite/PrisonerHubBreadcrumbsTest.php
- docroot/modules/custom/prisoner_hub_prison_access/src/EventSubscriber/QueryAccessSubscriber.php
- patches/computed_breadcrumbs-3243177-return-relative-urls-2.patch
- patches/computed_breadcrumbs-3266585-support-other-entity-types-2.patch
- patches/computed_breadcrumbs-3266585-support-other-entity-types-3.patch
This PR brings in breadcrumbs to the JSON:API response.
Breadcrumbs in JSON:API were required for two reasons:
1) It's easier/cleaner/quicker than having to request each parent category to build the breadcrumb trail. Avoiding having to include multiple parents, e.g. `?include=parent,parent.parent,parnet.parent.parent`
2) There doesn't appear to be a way of including _just_ the parent categories name, without having to include all fields.  `?include=parent.name` doesn't work (as `name` is not a relationship) and `?include=parent&fields[taxonomy_term--moj_categories]=name` also doesn't work.
To bring in the breadcrumbs into JSON:API, the module …
> Add breadcrumbs to jsonapi

- docroot/modules/custom/prisoner_hub_prison_access/src/EventSubscriber/QueryAccessSubscriber.php
Related to: https://trello.com/c/pm60I56L/711-implementation-of-sub-categories-design
When testing changes for sub-categories, I noticed there were JSON:API responses returning empty data sets. 
This is because unpublished content is not filtered out _early enough_.  So it ends up getting excluded after the list of contents has been generated.
This could lead to issues with pagination, where the first page has less than 40 items of content.
> Fix issue with empty JSON:API responses due to unpublished content

- docroot/modules/custom/prisoner_hub_taxonomy_sorting/prisoner_hub_taxonomy_sorting.install
Fixes an issue that was merged in with https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/353
Typo in the property name, the previous deployment would have run, but would have not updated everything in the database.
> Fix incorrect property being used in deployment script

- config/sync/core.base_field_override.node.link.promote.yml
- config/sync/core.entity_form_display.node.external_link.default.yml
- config/sync/core.entity_form_display.node.link.default.yml
- config/sync/core.entity_view_display.node.external_link.default.yml
- config/sync/core.entity_view_display.node.external_link.teaser.yml
- config/sync/core.entity_view_display.node.link.default.yml
- config/sync/core.entity_view_display.node.link.teaser.yml
- config/sync/field.field.node.external_link.field_show_interstitial_page.yml
- config/sync/field.field.node.link.field_display_url.yml
- config/sync/field.field.node.link.field_exclude_from_prison.yml
- config/sync/field.field.node.link.field_feature_on_category.yml
- config/sync/field.field.node.link.field_moj_episode.yml
- config/sync/field.field.node.link.field_moj_season.yml
- config/sync/field.field.node.link.field_moj_series.yml
- config/sync/field.field.node.link.field_moj_thumbnail_image.yml
- config/sync/field.field.node.link.field_moj_top_level_categories.yml
- config/sync/field.field.node.link.field_not_in_series.yml
- config/sync/field.field.node.link.field_prisons.yml
- config/sync/field.field.node.link.field_release_date.yml
- config/sync/field.field.node.link.field_show_interstitial_page.yml
- config/sync/field.field.node.link.field_summary.yml
- config/sync/field.field.node.link.field_url.yml
- config/sync/field.storage.node.field_show_interstitial_page.yml
- config/sync/field.storage.node.field_url.yml
- config/sync/node.type.link.yml
- config/sync/pathauto.pattern.link.yml
- config/sync/user.role.local_administrator.yml
- docroot/modules/custom/prisoner_hub_featured_content/tests/src/ExistingSiteJavascript/FeaturedContentFieldsFormTest.php
- docroot/modules/custom/prisoner_hub_taxonomy_field_ux/tests/src/ExistingSiteJavascript/TaxonomyFieldsFormStatesTest.php
- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.deploy.php
https://trello.com/c/KZhEpxrh/710-expand-concept-of-external-link-tile-to-cover-internal-links-and-remove-interstitial-page
- Rename `external_link` to `link`.  (This can only be done by creating a new content type, copying everything across, and then deleting the old one.  Another PR will be opened to delete the old one).
- Renamed `field_external_url` to `field_url`, and allow internal urls to be added.
- Added `field_show_interstitial_page`, with a default set to "on".
> Rename "external link" to "link"

- config/sync/field.storage.node.field_moj_top_level_categories.yml
- config/sync/field.storage.taxonomy_term.field_category.yml
- docroot/modules/custom/prisoner_hub_featured_content/js/prisoner-hub-featured-content.js
- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.install
Updates the category fields (on content and series) to accept just one value.
This includes bulk updating existing content/series with more than value.  Although most of which should have already been manually updated, there may still be some (including unpublished) content.
> Updating category field to be single value.

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.deploy.php
To avoid performance issues relating to clearing Drupal caches.
We will instead run these updates in batches, so that we don't clear the entire page cache in one time.
> Removing bulk update that removes featured content

- config/sync/views.view.taxonomy_overview.yml
https://trello.com/c/70QxDu0U/303-improve-visibility-of-taxonomy-in-drupal
This PR adds a Taxonomy overview page, featuring the bulk update tool.
The purpose for adding this now, is so that we can batch update categories to remove the featured content.  We found that doing it all in one go would cause performance issues due to cache's being cleared. See https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/372
It is also a card that is on the backlog, so something we wanted to do anyway.
The new page can be found underneath the content tab (I looked for somewhere to put it in "Structure" but there wasn't a good place. Having it under "Content" means it will be …
> Adds a taxonomy overview page, with bulk operations.

- docroot/modules/custom/prisoner_hub_breadcrumbs/src/NodeBreadcrumbBuilder.php
- docroot/modules/custom/prisoner_hub_breadcrumbs/tests/src/ExistingSite/PrisonerHubBreadcrumbsTest.php
https://trello.com/c/Q74RwuL2/735-extend-breadcrumb-to-all-pages-on-hub
Bugfix for content in a series.  The series was appearing at the beginning of the breadcrumb when it should be at the end.
> Setting correct order on breadcrumbs for content in a series.

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/views.view.content.yml
- config/sync/views.view.taxonomy_overview.yml
No, this is a small change that doesn't warrant a card.
Updates the /admin/content page to include the following bulk operation options:
A new filter on the /admin/content/taxonomy page that lets you search the parent category.  This field works across both series and categories, and takes into account parents that are 2 or 3 levels above. (I.e. if you search for "Leaving" you will get not just the sub-categories but also the sub-sub-categories).
> Add missing functionality from content+taxonomy overview pages

- config/sync/field.field.node.moj_radio_item.field_moj_thumbnail_image.yml
- config/sync/field.field.node.moj_video_item.field_moj_thumbnail_image.yml
This PR enables the alt tag field for thumbnail images on the audio and video content type.
It also makes this field required.
Previously this field was not enabled, meaning we are not capturing and outputting alt tag attributes for images on video and audio items.
Once the alt tag is required, you won't be able to update existing content without adding it.  Even if you were trying to update something unrelated to the image.
> Making the alt tag field required on thumbnail images.

- docroot/modules/custom/prisoner_hub_primary_nav/src/Resource/PrimaryNavResource.php
https://trello.com/c/KlX1FivQ/753-implement-primary-nav-bar
This PR fixes an issue where updating a prison (to add a menu) would not result in the cache being cleared.  Meaning the changes would not appear until the 3am cache clear cron run.
> Fix issue where cache for primary nav would not clear when a prison updated their menu

- composer.json
- docroot/sites/default/settings.php
- patches/flysystem_2772847-59-presigned-urls.patch
Related to: 
- https://trello.com/c/bD1oEkd0/826-re-instate-drupal-image-resizing-ddos-protection
- https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/383
Previous PR used a different method for stripping out the `?itok` parameter from resized image urls.  However, this didn't work in all situations - most notably via JSON:API, so image urls were considered invalid by s3.
This PR reverts back to using the `$config['image.settings']['suppress_itok_output'] = TRUE;` setting.  Which I initially thought was a security concern, but turns out that there is a separate setting that actually handles the DDoS protection (i.e. allowing images to be resized without a token).  I've updated the comments above the setting to explain this.
> Is …
> Revert method for stripping itok query param.

- composer.json
- patches/drupal-3057545-40.patch
Yesterday an error was discovered on prod, a series had been deleted that was being referenced from the Berwyn homepage.
When this happens, the referencing content should still work, but just not load in the deleted item.  However, the page crashed. There was a 500 error coming from the Drupal JSON:API response.
The issue was caused by the fact we are using a patch on Drupal core to allow it to support the `dynamic_entity_reference` module (which is used on the homepage so you can reference both content and series/categories).  The patch did not work with deleted entities.
I've updated the patch to fix the issue.
See https://www.drupal.org/project/drupal/issues/3057545#comment-14464137
> Is there any additional information …
> Fixing 500 error when a referenced entity is deleted.

- config/sync/system.site.yml
This sets the homepage in Drupal as the /admin/content page.  This means when a user logs in, they are immediately taken to this page (rather than the /user page).
The previous homepage was /user/login, which presented a logged out user with a login form.  
However as the /admin/content page is not accessible when logged out, the user will still see the login form (so it will appear the same as it did before).  There is a small difference:
Before:
After:
> Setting the content overview page as the homepage.

- config/sync/core.extension.yml
- docroot/modules/custom/prisoner_hub_sub_terms/README.md
- docroot/modules/custom/prisoner_hub_sub_terms/prisoner_hub_sub_terms.info.yml
- docroot/modules/custom/prisoner_hub_sub_terms/prisoner_hub_sub_terms.routing.yml
- docroot/modules/custom/prisoner_hub_sub_terms/src/Resource/SubTerms.php
- docroot/modules/custom/prisoner_hub_sub_terms/tests/src/ExistingSite/PrisonerHubSubTermsTest.php
https://trello.com/c/Ar0dte1r/820-change-sorting-of-subcats-series-to-show-relevant-order-in-specific-prisons
Provides a new custom jsonapi resource for sub-categories and series:
`/jsonapi/prison/{prison name}}/taxonomy_term/moj_categories/{uuid}/sub_terms`
This is ordered by the most recently updated content (in the current prison).
The current method for retrieving sub-categories and series will continue to work.  A subsequent PR is needed to clean up the old method for sorting by content updated date (as there were performance issues related to this).
> Adding jsonapi resource for sub terms.

- config/sync/core.extension.yml
- config/sync/user.role.local_administrator.yml
- config/sync/user.role.moj_local_content_manager.yml
A previous PR (todo find PR) uninstalled the views_unpublished module, it was considered to be no longer required.
However, we have since found it is still required, as otherwise DCMs (local content managers) cannot view unpublished content.
This PR adds back in the module, and configures it so that all content types excluding help pages can be viewed unpublished.
When a new content type is added, it will need to be included as a permission.
> Re-enabling view_unpublished module

- config/sync/user.role.moj_local_content_manager.yml
Currently, DCM's (local content managers) can only edit content owned by their own prison.
However, the bulk update tool circumnavigates these restrictions, so they could use this to publish content that was owned by another prison.
The reason for this is that the restrictions on editing content are only placed on the content edit form, and are not global permissions.
> Removing permissions to use bulk update tool

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.install
Fixes issue with deployment of https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/393
The above PR installed the publication_date module, this failed to install properly on prod.  The error was 
```
Error Output:
================
In DiscoveryTrait.php line 53:
The "field_item:published_at" plugin does not exist
```
I'm not 100% sure why this happened (and only occurred on prod).  It looks as though the post-install hook ran too early, and the code wasn't there (as the plugin mentioned above should have been available).  Possibly there is a cache of the plugins that wasn't cleared in time.
Either way, the issue now is that the module is technically installed, but it didn't create the necessary column in the database, and didn't run …
> Fixing failed publication date module install.

- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.install
Currently the main branch has https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/395 ready to be released.  However this is leading to data loss due to incorrect data in the db.
A previously deployed update set all secondary tags as topics:
https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/379/files#diff-b37e71fa6362842ef896c7076b00111f0965002dbcd125b843347f84d92e030bR346-R351
Although this worked, it did not update some of the field data in the db, to mark it with the new taxonomy type.
This incorrect db data was not causing any issues, however by removing the secondary tags taxonomy completely, it meant Drupal "tidied up" it's data, and cleared out the field data.
This PR updates the field data by running …
> Update/remove incorrect taxonomy data in the db.

- docker-compose.circleci.yml
Fixes issue with mariadb not working, resulting in test runner not being able to run on other PRs.
The solution was to fix to a version of mariadb, the same version as used on prod.
This was the error from the latest version:
```
circleci@0b2e180760bc:~/workspace$ docker-compose -f docker-compose.circleci.yml logs prisoner-content-hub-backend-db
Attaching to workspace_prisoner-content-hub-backend-db_1
prisoner-content-hub-backend-db_1     | 2022-05-25 10:01:16+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.8.3+maria~jammy started.
prisoner-content-hub-backend-db_1     | 2022-05-25 10:01:16+00:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
prisoner-content-hub-backend-db_1 …
```
> Fix mariadb not working on circleci

- Dockerfile
- helm_deploy/prisoner-content-hub-backend/templates/drupal-post-install-hook.yaml
https://trello.com/c/wqt78xna/1008-allow-dcms-and-studio-admins-to-continue-using-drupal-during-deployments
The previous PR https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/410 added in this functionality, this PR enables the deployment.
> Enable readonly on deployments

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/views.view.taxonomy_overview.yml
https://trello.com/c/HK5LEtQ4/1029-help-dcms-understand-how-the-new-homepage-updates-section-works
This makes updates to the Taxonomy overview page:
- Adds a "Include in homepage updates" filter, so that there is a way to show all of the subcategories/series that are included in homepage updates.  (This is the primary reason for this PR, to give DCM's a place where they can see this list).
- Improved UX, split filters out into groups.  Converted "Vocabulary" dropdown to be called "Type" and have checkboxes.
- Added additional columns to the results, to show more data
- Fixed issue where searching for parent category wasn't bringing back content inside a series that was …
> Updating taxonomy overview page

- config/sync/field.field.taxonomy_term.series.field_sort_by.yml
https://trello.com/c/qBzmYtwt/1100-bulk-update-series-to-use-release-date-sorting
Small change that will effect new series created in Drupal. 
The default value for how a series is sorted will now be using release dates.  As release date sorting is more appropriate for most series.
> Set the default value for new series to be release date

- config/sync/core.entity_form_display.node.homepage.default.yml
- config/sync/field.field.node.homepage.field_featured_tiles.yml
- config/sync/field.field.node.homepage.field_key_info_tiles.yml
- config/sync/field.field.node.homepage.field_large_update_tile.yml
- docroot/modules/custom/prisoner_hub_cms_help/prisoner_hub_cms_help.module
- docroot/profiles/prisoner_content_hub_profile/prisoner_content_hub_profile.profile
- docroot/themes/custom/prisconhub/css/styles.css
- docroot/themes/custom/prisconhub/prisconhub.theme
https://trello.com/c/HK5LEtQ4/1029-help-dcms-understand-how-the-new-homepage-updates-section-works
This PR updates the fields on the new homepage content type:
- Adds a "How does this work?" link
- Updates the descriptive text around the fields and places them into groups.
- For reference fields that support switching to the "Taxonomy Term" type (e.g. Key Info Tiles, and Featured Tiles).  The label "Taxonomy term" is changed to list out the types of taxonomy that can be selected.
> Improve homepage fields

- config/sync/core.entity_form_display.node.moj_radio_item.default.yml
A config change on local was accidentally exported and pushed up to prod.  This was displaying the series field on the audio content type as a long list of radio buttons.  This PR reverts it back to a select2 field.
> Revert series field back to select2, accidentally updated.

- apache/apache2.conf
https://trello.com/c/q0qy0xKe/814-fix-apache-error-in-logs-related-to-performance
This change is based on recommendation here https://serverfault.com/questions/693708/how-to-resolve-info-server-seems-busy-from-apache-server-logs
Because we have limited visibility on the issue (we don't have great monitoring tools, we don't have a devops/sysadmin type expert).  We are going to increase this setting in small amounts, to see if there are any improvements.
There's not a huge amount of documentation on this setting.  But the Apache docs says _"Setting this parameter to a large number is almost always a bad idea."_. Although without specifying what the consequences are.
https://httpd.apache.org/docs/2.4/mod/prefork.html#maxspareservers
It's likely that …
> Increase MaxSpareServers from default of 10 to 18.

- helm_deploy/prisoner-content-hub-backend/values.yaml
https://trello.com/c/q0qy0xKe/814-fix-apache-error-in-logs-related-to-performance
By increasing the number of pods in the service, we increase the amount of available processes Apache can handle.  The default is 256 per Apache server (so we'd be increasing from 768 simultaneous connections to 1280).
I looked at increasing the number of MaxRequestWorkers, but the method for working this out is:
```
total available memory / average process size
```
So in our case it would be:
```
2000 / 73 = 27
```
This therefore suggests decreasing the number, which would make the problem worse.
See related google doc: https://docs.google.com/document/d/1d0lkte2tgEuPjRW5VjQfZRtRqsP4yTkmjmUU0wMdUcg/edit#
We're also removing `maxReplicaCount`, as this isn't being used. …
> Increase replica count to 5

- config/sync/core.base_field_override.node.urgent_banner.promote.yml
- config/sync/core.base_field_override.node.urgent_banner.title.yml
- config/sync/core.entity_form_display.node.page.default.yml
- config/sync/core.entity_form_display.node.urgent_banner.default.yml
- config/sync/core.entity_view_display.node.urgent_banner.default.yml
- config/sync/core.entity_view_display.node.urgent_banner.teaser.yml
- config/sync/field.field.node.urgent_banner.field_exclude_from_prison.yml
- config/sync/field.field.node.urgent_banner.field_more_info_page.yml
- config/sync/field.field.node.urgent_banner.field_prison_owner.yml
- config/sync/field.field.node.urgent_banner.field_prisons.yml
- config/sync/field.storage.node.field_more_info_page.yml
- config/sync/node.type.urgent_banner.yml
- docroot/modules/custom/prisoner_hub_prison_access_cms/tests/src/ExistingSite/PrisonerHubPrisonAccessCmsTest.php
https://trello.com/c/Isn6DtTl/997-allow-prisoners-to-see-urgent-notices-in-the-banner
Creates the urgent banner content type in Drupal.
Still todo:
DCMs should only be allowed to publish to their own prison (and not other prisons).
> Creating urgent banner content type.

- docroot/modules/custom/prisoner_hub_explore/src/Resource/Explore.php
Fix for https://sentry.io/organizations/ministryofjustice/issues/3451881467/?referrer=slack
The explore the hub query (to get random content) was not excluding certain content types such as the help_page and urgent_banner.  These cause an error when used with `?include=field_moj_thumbnail_image` as the field does not exist on these types.
The fix was to add a check that this image field exists.  
> Fix for errors relating to missing image field.

- config/sync/user.role.local_administrator.yml
- config/sync/user.role.moj_local_content_manager.yml
After releasing the homepage we noticed that studio admins (and DCMs) can't see or edit the publication date.  This makes it difficult to get content to appear on the "recently added" component (amongst other things).
The permissions have already been added on production, this PR updates the config as code, to prevent the change from being reverted on the next deploy.
> Adding permissions to see and edit the publication date.

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/editor.editor.basic_html.yml
- config/sync/editor.editor.full_html.yml
- config/sync/filter.format.basic_html.yml
- config/sync/filter.format.full_html.yml
- config/sync/image.style.linkit_result_thumbnail.yml
- config/sync/linkit.linkit_profile.default.yml
- config/sync/pathologic.settings.yml
- patches/linkit-2877535-link-shown-after-autocomplete-is-bare-41.patch
- patches/pathologic-758118-wildcard-for-additional-paths-18.patch
https://trello.com/c/ZTW15U4f/1387-prevent-urls-that-wont-work-from-being-used-in-the-texteditor
Installs a module called `pathologic` which adds a text filter to update urls.  The configuration has been setup to convert urls to be relative.  Therefore urls like `https://wayland.content-hub.prisoner.service.justice.gov.uk/tags/1282` will become `/tags/1282`.
Also enables a module called `linkit` which allows the user to search for the title of content/taxonomy instead of copy pasting the url.
> Fix absolute urls being used in the text editor.

- config/sync/filter.format.basic_html.yml
- config/sync/filter.format.full_html.yml
For some reason Drupal wants to re-order this config, so it's re-importing it on every deployment.
This PR adds it in the correct format, so that it doesn't get picked up as a new config change.
> Re-exporting config that Drupal seems to want to always re-order.

- apache/apache2.conf
- docroot/sites/default/settings.php
No this is a small change.  Not 100% sure we want do this yet, up for discussion.
The Apache timeout directive has a default of 60 seconds https://httpd.apache.org/docs/2.4/mod/core.html#timeout
For some reason ours is set to 5 minutes (not sure why it was increased).
This PR sets it to 30 seconds, to match the timeout from the frontend.
Are there any requests that take longer than 30 seconds?
There shouldn't be, at least not from the frontend.
There are some cli requests that do, but these do not run through Apache, so won't be subject to this timeout.
Possibly there are some long running processes in the CMS?  But anything that takes over 30 seconds should really be split into a batch.
> Decrease timeout to 30 seconds, to match the timeout on the frontend.

- docroot/modules/custom/prisoner_hub_cms_help/prisoner_hub_cms_help.module
Clean up the logs by removing a common PHP warning about an undefined variable.
> Fix for undefined variable.  That is often appearing in the logs.

- config/sync/search_api.index.content_for_search.yml
https://trello.com/c/CEwYySkj/1444-move-search-queries-to-go-directly-from-the-frontend-to-elasticsearch
To allow search queries to be run from the f/e, this PR adds the prison machine_name (which can either be a specific prison, or a prison category, e.g. `adult_male`).  And the exclude from prison machine name (this will always be a specific prison, and never a category).
After these have been added, the conditions can be added to the elastic search query.  
> Adding prison machine names to elasticsearch

- config/sync/core.extension.yml
- docroot/modules/custom/jsonapi_filter_cache_tags/README.md
- docroot/modules/custom/jsonapi_filter_cache_tags/jsonapi_filter_cache_tags.info.yml
- docroot/modules/custom/jsonapi_filter_cache_tags/jsonapi_filter_cache_tags.install
- docroot/modules/custom/jsonapi_filter_cache_tags/jsonapi_filter_cache_tags.module
- docroot/modules/custom/jsonapi_filter_cache_tags/jsonapi_filter_cache_tags.services.yml
- docroot/modules/custom/jsonapi_filter_cache_tags/src/CacheTagsBuilder.php
- docroot/modules/custom/jsonapi_filter_cache_tags/src/EventSubscriber/ResponseSubscriber.php
https://trello.com/c/g4cjHCyT/1585-prevent-certain-jsonapi-requests-from-having-their-cache-regularly-cleared
Fix performance issues when content is updated during peak hours.  The issue we've been seeing is that due to Drupal's default use of the generic `node_list` cache tag, this results in any content updates invalidating all series/topics pages, the content component on category pages, and the updates section on the homepage.  When done during high traffic periods, Drupal has to rebuild the cache for all of these pages at the same time.
This PR adds a custom module that adds cache tags based on jsonapi filter values.  So we only end up invalidating the requests we need to.
For more info on cache tags see …
> Improve performance by reducing unnecessary cache invalidations.

- docroot/modules/custom/prisoner_hub_sub_terms/README.md
- docroot/modules/custom/prisoner_hub_sub_terms/prisoner_hub_sub_terms.info.yml
- docroot/modules/custom/prisoner_hub_sub_terms/prisoner_hub_sub_terms.module
- docroot/modules/custom/prisoner_hub_sub_terms/src/Resource/SubTerms.php
- docroot/modules/custom/prisoner_hub_sub_terms/src/SubTermsCacheTagInvalidator.php
- docroot/modules/custom/prisoner_hub_sub_terms/tests/src/ExistingSite/PrisonerHubSubTermsTest.php
https://trello.com/c/g4cjHCyT/1585-prevent-certain-jsonapi-requests-from-having-their-cache-regularly-cleared
This PR improves performance by reducing the number of cache invalidations for subcategory pages.
- Only the direct parent category will be invalidated, and not parents of that.  
- We only invalidate when content is published, not when existing published content is updated. 
> Reducing cache tag invalidations on category pages.

- docroot/modules/custom/prisoner_hub_sub_terms/src/SubTermsCacheTagInvalidator.php
- docroot/modules/custom/prisoner_hub_sub_terms/tests/src/ExistingSite/PrisonerHubSubTermsTest.php
Fixes an issue introduced by https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/450
The above PR changed how cache invalidations worked for the "In this section" component.
Now only new content being published in a category or series will trigger a cache invalidation.
This PR takes into account already published content, that is being switched from one category/series to another.
> Invalidate cache when switching to a new category or series.

- docroot/sites/default/settings.php
Reverts ministryofjustice/prisoner-content-hub-backend#455
Once https://github.com/ministryofjustice/cloud-platform-environments/pull/8816 has been deployed we should re-enable Redis in Drupal
> Revert "Temporarily disable redis as it is currently not responding correctly."

- helm_deploy/prisoner-content-hub-backend/db-backup.sh
https://trello.com/c/JnaHKTyN/758-improve-drupal-database-backups
We found that there are intermittent DNS issues with this cronjob.  Other services have reported similar.  The fix is to retry the connection.
https://mojdt.slack.com/archives/C57UPMZLY/p1664264969450269
Because mysqldump doesn't have a `--retry` option (like curl does), we do this manually by running a simple 'SELECT 1' command, twice, before the mysqldump command.
> Fix for intermittent DNS issue with cronjob

- config/sync/core.extension.yml
- config/sync/views.view.taxonomy_overview.yml
Fixes a bug where Topics aren't shown on the https://manage.content-hub.prisoner.service.justice.gov.uk/admin/content/taxonomy page
> Fix topics not showing on taxonomy overview page.

- config/sync/raven.settings.yml
I'm trying to reduce noise on the #hub_alerts_prod channel.  We get quite a few clientside js errors from Drupal.  They are normally related to third party code (either from Drupal or ckeditor) and is not possible to replicate on another environment.  I.e. they are not possible to fix, and often don't actually represent a real issue.
I looked into a way to stop these types of errors from making it through to Slack (whilst still retaining PHP errors) but couldn't see a way.  I therefore think it's easier to just disable them altogether.  We've had them enabled for over a year and have never found them to be useful.
> Are there any steps required …
> Disabling Sentry JS error reporting.

- docroot/sites/default/settings.php
https://trello.com/c/4tKSi5ng/1713-spike-video-transcoding
Adds CacheControl headers to s3 files.  After this has been merged, all uploaded files will get the
`CacheControl' => 'max-age=7890000, public',` header (i.e. cache for 3 months).
For existing files, we can update the metadata using the aws cli:
```
aws s3 cp s3://my-bucket/ s3://my-bucket/ --recursive --metadata-directive REPLACE \
--cache-control "max-age=7890000, public" --acl private
```
Note that this command updates all of the files in the bucket.  I ran this on the dev bucket and it too approx 2 hours.  However, there would have been no downtime, as all it is doing is updating files within S3.
Although we are setting the max-age to 3 months, we will currently only get a maximum of 24 …
> Set cache control headers for all files in s3.

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/views.view.content.yml
- config/sync/views.view.taxonomy_overview.yml
- patches/views_data_export-allow-configurable-filesystems_3200974-6.patch
https://trello.com/c/Z2dQZ0A5
Add a CSV export option to the /admin/content and /admin/content/taxonomy pages.
Previously we were unable to do this as there wasn't any integration between the export module and S3.  But there is now a patch that lets us use S3.
> Adding CSV export option

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/views.view.taxonomy_map.yml
- docroot/modules/custom/prisoner_hub_taxonomy_field_ux/prisoner_hub_taxonomy_field_ux.module
- docroot/modules/custom/prisoner_hub_taxonomy_field_ux/src/Plugin/views/field/DynamicParentCategoryViewsField.php
- patches/views_tree-3298991-undefined-function-getIterator.patch
https://trello.com/c/fQZgmmiD/1876-taxonomy-map-page-in-drupal-that-displays-full-taxonomy-hierarchy
Creates a "Taxonomy Map" page to show the full hierarchy of subcategories and series.
> Adding taxonomy map page.

- Makefile
Fix issue deploying https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/495
An additional cache rebuild is required, to pick up new module locations.
> Add additional cache rebuild before maintenance mode is enabled

- config/sync/field.field.node.link.field_moj_thumbnail_image.yml
- config/sync/field.field.node.moj_pdf_item.field_moj_thumbnail_image.yml
- config/sync/field.field.node.moj_radio_item.field_moj_thumbnail_image.yml
- config/sync/field.field.node.moj_video_item.field_moj_thumbnail_image.yml
- config/sync/field.field.node.page.field_moj_thumbnail_image.yml
- config/sync/field.field.taxonomy_term.moj_categories.field_moj_thumbnail_image.yml
- config/sync/field.field.taxonomy_term.series.field_moj_thumbnail_image.yml
- config/sync/field.field.taxonomy_term.topics.field_moj_thumbnail_image.yml
…
https://trello.com/c/Sb2D4Zgh/950-remove-alt-text-from-thumbnail-field-for-all-content-types-and-taxonomies
Create any content type or taxonomy that has a thumbnail image field. Upload an image. Before this change, after uploading an image, an edit control would appear for mandatory alt text. The content would not be saveable without alt text.
With this change, the alt text edit box is not presented, and the content can still be saved without filling it in.
This removes the prompt to add mandatory alt-text when uploading an image.
No
> Is there any additional information that …
> 🔧 disable alt-text on thumbnail images for all content types and taxonomy vocabularies with a thumbnail.

- .gitignore
- composer.json
- composer.lock
https://trello.com/c/PjmirJ6p/2107-update-jsonapi-image-styles-module
View any page containing images.
This PR updates the version constraint for the JSON:API Image Style modules from the 2.x to 3.x branch. It also updates the installed version of the module to 3.0.0. 
No
No
Yes. This must be deployed in conjunction with https://github.com/ministryofjustice/prisoner-content-hub-frontend/pull/635
> Update jsonapi image styles

- config/sync/editor.editor.basic_html.yml
- config/sync/editor.editor.full_html.yml
- config/sync/filter.format.basic_html.yml
https://trello.com/c/oAlFYW7K/2117-dont-expose-options-in-the-rich-text-editor-that-have-no-effect-in-the-front-end
Create a page in Drupal that has h5 and h6 elements in rich text.
View the content in the front end.
These elements will not be styled.
Remove the option to add h5 and h6 elements in the rich text editor for Basic HTML and Full HTML text formats.
This PR does not address the image alignment portions of the ticket; they are being implemented on the front end.
No
> Are there any steps required …
> 🔧  remove h5 and h6 tags from ckeditor5 configurations - these are not styled in the front end.

- helm_deploy/prisoner-content-hub-backend/s3-sync-temp.sh
- helm_deploy/prisoner-content-hub-backend/templates/_envs.tpl
- helm_deploy/prisoner-content-hub-backend/templates/s3-sync-temp.yaml
- helm_deploy/prisoner-content-hub-backend/values.development.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
https://trello.com/c/LgNVXNpA/2113-spike-investigate-how-to-move-prod-s3-bucket-from-ireland-to-london
N/A
🔧  Add new s3-sync-temp.envs section to values.yaml to contain environment variables used by sync jobs to identify s3 bucket to sync to and from.
🔧  Enable syncing to the new bucket in development environment only. Default to off in all other environments.
🔧  Switch development environment Drupal instance to use original bucket so that that environment is usable for front end development.
🔨  New s3-sync-temp.sh script for syncing staging to new s3 buckets. This is a copy of the existing s3-sync.sh script used for …
> Sync new development s3 bucket from existing staging data 

- config/sync/update.settings.yml
https://trello.com/c/grIV143g/2134-configure-module-update-notification-email-address
N/A
The configuration for the update manager module is changed to 
* only send emails for security updates, rather than all available updates
* send such updates to a real email address rather than admin@example.com
No
No
No
> 🔧  use a real email address for update notifications. Only notify for security updates.

- helm_deploy/prisoner-content-hub-backend/values.development.yaml
This will keep the new dev bucket in sync with changes made by content editors until we switch to the new bucket.
N/A
There is a temporary sync cron job that was used to sync the new dev bucket from the existing staging bucket. Now this sync is complete, we want to stay up to date with any further changes made by content editors, which are still using the original Irish S3 prod bucket. This PR changes the region from which we run the temporary sync to Ireland.
No.
> Is there any additional information that …
> 🔧  switch temp sync region to be Ireland, so we can sync new dev bucket from old prod. 

- helm_deploy/prisoner-content-hub-backend/s3-sync-temp.sh
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
N/A
There is a temporary sync job. This previously sync'd the new prod s3 bucket in London with the staging bucket, to get the majority of the contents from the same region. Now that has been completed, we now want to sync the new prod bucket from the old one which is still use by the prod application. Then when we want to cut over to the new prod bucket it will already be up to date.
No
No
> Are there any steps required when …
> Update s3 temp sync region in prod

- helm_deploy/prisoner-content-hub-backend/values.development.yaml
This can now return to just updating every night. 
N/A
We introduced a new job for sync'ing dev s3 first from staging, then from the old prod bucket, so that the bulk of the content didn't have to be copied across regions. This has now been proven, has been replicated on prod, and is hence no longer required in dev.
This PR removes this temporary sync'ing mechanism on dev.
No
No
> Are there any steps required when …
> 🔧  turn off temporary synchronisation of old prod to new dev s3 buckets every 15 minutes.

- helm_deploy/prisoner-content-hub-backend/templates/_envs.tpl
N/A
We were previously editing drupal-s3-output-temp to point to the same location as drupal-s3-output when we wanted to change the sync source from staging to old prod. However this secret was overwritten by subsequent terraform applications. 
Since https://github.com/ministryofjustice/cloud-platform-environments/pull/13199, drupal-s3-output is now available in prod, so we can just change the  envs to use that instead.
No.
No
> …
> Switch from using drupal-s3-output-temp to drupal-s3-output to point temporary sync.

- helm_deploy/prisoner-content-hub-backend/values.production.yaml
N/A
This bucket switches the s3 bucket used by the production system from the old one to the new one.
This also disables the regular job that sync'd the contents of the old bucket to the new.
No.
No
See deployment plan: https://docs.google.com/document/d/1NaLltCEmFHE0w748F3--UwgGCx306Wkuy1YtM98Wy8o/edit#
> 🗃️  start using the new s3 bucket in prod, and stop syncing old bucket to the new one.

- helm_deploy/prisoner-content-hub-backend/templates/_envs.tpl
- helm_deploy/prisoner-content-hub-backend/values.production.yaml
- helm_deploy/prisoner-content-hub-backend/values.yaml
N/A
This PR changes the source bucket for the overnight sync from prod to dev and staging, to use the new prod bucket in eu-west-2.
No
No
This PR should not be deployed until after https://github.com/ministryofjustice/prisoner-content-hub-backend/pull/534 has been deployed to prod and use of the new bucket in prod tested.
See deployment plan: …
> Use new s3 bucket for dev staging overnight sync

- composer.lock
https://trello.com/c/vO5BiuwU/43-string-field-formatter
N/A
Updates String Field Formatter from 2.0.0 to 2.0.2 for Drupal 10 compatibility.
No
No
No
> Update String Field Formatter module for Drupal 10 compatibility.

- composer.lock
https://trello.com/c/aSP7MSlY/47-views-exposed-form-fieldset
N/A
Updates Views Exposed Form Fieldset module for D10 compatibility.
Updates composer.lock to specify version 8.x-1.6 of that module. 
No
No
No
> ⬆️  update Views Exposed Form Fieldset for D10 compatibility.

- composer.lock
https://trello.com/c/ROklWtZP/2177-update-all-contrib-modules
N/A
Updates many drupal contrib projects and their composer dependencies:
```
- Upgrading aws/aws-crt-php (v1.0.2 => v1.2.2)
- Upgrading aws/aws-sdk-php (3.253.1 => 3.279.3)
- Upgrading chi-teck/drupal-code-generator (2.6.1 => 2.6.2)
- Upgrading composer/ca-bundle (1.3.5 => 1.3.6)
- Upgrading consolidation/annotated-command (4.7.1 => 4.9.1)
- Upgrading consolidation/output-formatters (4.2.3 => 4.3.2)
- Upgrading consolidation/self-update (2.0.5 => 2.2.0)
- Upgrading cweagans/composer-patches (1.7.2 => 1.7.3)
- Downgrading dflydev/dot-access-configuration …
```
> ⬆️  update all the things.

- config/sync/elasticsearch_connector.cluster.opensearch.yml
- config/sync/search_api.server.elasticsearch.yml
- docker-compose.yml
- docroot/modules/custom/prisoner_hub_prison_access/tests/src/ExistingSite/PrisonerHubQueryAccessSearchApiTest.php
- docroot/sites/default/settings.php
- helm_deploy/prisoner-content-hub-backend/templates/_envs.tpl
- helm_deploy/prisoner-content-hub-backend/values.yaml
- prisoner-content-hub-backend.env
https://dsdmoj.atlassian.net/browse/LNP-272
N/A
Switch out Elasticsearch for Opensearch, as Elasticsearch is no longer supported by cloud platform team. 
Disables existing elasticsearch cluster (this will be removed at a later date)
Adds an opensearch cluster
Move existing search index configuration to the new server
Update docker configuration to use opensearch in local and CI environments
No
No
This must be deployed in tandem with …
> LNP-272: move from elasticsearch to opensearch

- .circleci/config.yml
https://dsdmoj.atlassian.net/browse/LNP-626
Push a branch and watch CircleCI fail to build.
This must be done in one of the brown out times outlined in https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176 or after the deprecation date of 30/09/24.
Swap the deprecated docker image used by CircleCI for the default, which should never be deprecated.
No
No
No
> LNP-626: fix deprecated CircleCI docker image.

- composer.json
- composer.lock
- config/sync/config_ignore.settings.yml
- config/sync/core.extension.yml
- config/sync/filter.format.basic_html.yml
- config/sync/filter.format.full_html.yml
- config/sync/pathologic.settings.yml
- patches/pathologic-758118-wildcard-for-additional-paths-19.patch
https://dsdmoj.atlassian.net/browse/LNP-580
N/A
Updates core and contrib modules. Removes/rerolls patches as necessary.
No
No
A follow is required to remove the config_filter module. This was previously an implicit requirement for this project via the dependencies of the config_ignore module. This PR updates the major version of config_ignore that no longer requires config_filter, but we cannot remove config_filter from the filesystem whilst it …
> LNP-580: core & contrib updates

- config/sync/block.block.prisconhub_breadcrumbs.yml
- config/sync/block.block.prisconhub_secondary_local_tasks.yml
- docroot/themes/custom/prisconhub/prisconhub.info.yml
https://dsdmoj.atlassian.net/browse/LNP-685
Visit a page with secondary tasks, for example /admin/config/development/configuration as an administrator and compare it to the same page running with the Claro theme. You will see the Breadcrumbs and secondary tasks (Full archive | Single item) components of the page are missing.
This change manually adds the regions from Claro to the Prisconhub subtheme as per https://www.drupal.org/docs/develop/theming-drupal/creating-sub-themes#s-inheriting-theme-regions
It also moves the secondary tasks to the correct newly available region.
Yes. …
> LNP-685: 🐛  fix region inheritance in prisconhub theme.

- docroot/modules/custom/prisoner_hub_bulk_updater/src/Drush/Commands/PrisonerHubBulkUpdaterCommands.php
https://dsdmoj.atlassian.net/browse/LNP-833
N/A
Creates a new drush command. This can be run on a server passing a prison machine name, and a file name containing a list of node ids. 
The drush command will exclude all the content passed from the given prison.
The file must reside in the docroot/modules/custom/prisoner_hub_bulk_updater/files folder.
No
No
Deploying the PR will not exclude the content. It is necessary to run the drush command …
> LNP-833: Hide Red Content at Chelmsford

- Dockerfile
https://dsdmoj.atlassian.net/browse/LNP-834
N/A
Updates the version of PHP used by the Drupal Apache/PHP docker image from 8.1.11 to the latest 8.1.29.
Also updates the underlying version of Debian from Buster to Bookworm as PHP 8.1.29 is not available on Buster.
No
No
No
> Task/LNP:-843: Update PHP from 8.1.11 to  8.1.29

- docroot/modules/custom/prisoner_hub_bulk_updater/prisoner_hub_bulk_updater.services.yml
- docroot/modules/custom/prisoner_hub_bulk_updater/src/Drush/Commands/PrisonerHubBulkUpdaterCommands.php
- docroot/modules/custom/prisoner_hub_prison_access_cms/prisoner_hub_prison_access_cms.module
https://dsdmoj.atlassian.net/browse/LNP-835
View the admin/content screen - you will see content that is attributed to the same prison multiple times.
* Fixes the implementation of hook_entity_presave() that caused the duplication of items in the relevant prison fields.
* Implements a drush command `drush phdpf` that identifies all nodes in the database with this problem, and resaves them with deduped fields.
No
No
The drush command requires …
> Bug/LNP-835: duplicate prison field values

- Dockerfile
https://dsdmoj.atlassian.net/browse/LNP-867
Build a local docker based Drupal development environment. xDebug will not be installed.
Updates the version of xDebug to one compatible with PHP 8.3.
No.
No.
No.
> LNP-867: 🐘  update version of xDebug to be compatible with PHP 8.3.

- .circleci/config.yml
- Dockerfile
- Makefile
- composer.json
- composer.lock
- docroot/modules/custom/prisoner_hub_edit_only/src/Controller/EntityViewOverride.php
- docroot/modules/custom/prisoner_hub_prison_access/tests/src/ExistingSite/PrisonerHubQueryAccessTestBase.php
- docroot/modules/custom/prisoner_hub_recently_added/src/Resource/RecentlyAdded.php
- docroot/modules/custom/prisoner_hub_sub_terms/src/Resource/SubTerms.php
- docroot/modules/custom/prisoner_hub_taxonomy_field_ux/tests/src/ExistingSiteJavascript/TaxonomyFieldsFormStatesTest.php
- docroot/modules/custom/prisoner_hub_taxonomy_sorting/src/EntityPreSave.php
- phpstan.neon
https://dsdmoj.atlassian.net/browse/LNP-879
N/A
* adds phpstan-drupal and its dependencies to the dev requirements in composer, to make phpstan available in local and CI environments
* adds a command to the Makefile for running phpstan
* adds a configuration file for phpstan, and makes sure it is copied to docker environments in the Dockerfile
* adds running of phpstan to the run-tests section of the CircleCI configuration
* fixes all issues in the current codebase identified by phpstan running at level 1
* incompatible overridden methods, eg where explicit return types are missing
* removal of use of potentially …
> LNP-879 PHPStan level 1 in CI

- docroot/modules/custom/prisoner_hub_recently_added/src/Resource/RecentlyAdded.php
trim priority content to half the required value before loading non-priority content. This fixes the issue where non-priority content tries to load 0 entries and then crashes.
Also return early if trying to load 0 items in the recently-added endpoint. This can still happen despite the above if the requested page size is 1 - this leads to 1 item of priority content (if there is any) and 0 items of non-priority content.
https://dsdmoj.atlassian.net/browse/LNP-952
Prioritise lots of content. Attempt to load a prison home page.
Trims the size of the set of prioritised content before working how much non-prioritised content to …
> LNP-718: 🐛  fix bug in recently-added endpoint

- Makefile
- helm_deploy/prisoner-content-hub-backend/db-backup.sh
https://dsdmoj.atlassian.net/browse/LNP-968
Adds flags to the mysqldump command run to take exports from production, so that when the dump is imported into other environments, the existing database will be dropped and recreated before the exported data is imported.
This ensures that any tables that exist eg in dev but not prod are removed on import. This stops issues where for example Drupal tries to create a table in a post-install action and fails because it unexpectedly exists.
No
No
> Are there any …
> LNP-968: 🔥  drop target database before importing database dump.

- Makefile
- helm_deploy/prisoner-content-hub-backend/db-backup.sh
- helm_deploy/prisoner-content-hub-backend/db-refresh.sh
https://dsdmoj.atlassian.net/browse/LNP-975
Try to run make-sync locally. The script will try to delete a database with the same name as the prod database, and fail.
In LNP-968, we addressed the problem that during a database refresh, tables that were on the target system but not in the database dump would still be present after refresh.
That change built the dropping and recreation of the target database into the dump file. However, because that embeds the database name, and the database name is different across environments, this would not work.
This PR refactors that to move the dropping and recreation of the target …
> LNP-975 account for different db names when refreshing db

- helm_deploy/prisoner-content-hub-backend/db-refresh.sh
[LNP-975](https://dsdmoj.atlassian.net/browse/LNP-975)
Note there was a previous merge to main for this ticket, which did not fix the problem that has only been pushed as far as staging.
Imports of the database backup to environments currently fail.
Adds the username, password, and host to a new [mysqladmin] section in the temporary my.conf used when importing backups. This allows mysqladmin to drop and recreate the target database before importing the dump.
No
No
> Are there any steps required when …
> LNP-975: 🗃️  mysqladmin cant connect during refresh

- config/sync/views.view.content.yml
https://dsdmoj.atlassian.net/browse/LNP-1017
* Go to /admin/content.
* Try to filter content by Urgent Banner content type.
* Fail because that option doesn't exist
Adds Urgent Banner to content type filter option.
No
No
No
> LNP-1017: 🐛  content could not be filtered by Urgent Banner.

- php/xdebug.ini
https://dsdmoj.atlassian.net/browse/LNP-1084
N/A
* Adds the zend_extension line to the ini as a comment so it's easier to turn xdebug on and off
* Sets the xdebug port explicitly to 9000
No
No
No
> LNP-1084: 🥃  set xdebug port explicitly in ini file.

- docroot/themes/custom/prisconhub/prisconhub.theme
https://dsdmoj.atlassian.net/browse/LNP-1095
Edit a translated node or taxonomy term.
Implements a form alter hook to the administration theme that will remove specific named field groups from content editing forms when editing in the non-default language.
No
No
No
> LNP-1095: 💄  remove empty field groups from translated forms.

- Dockerfile
- docker-compose.override.yml
- php/spx.ini
https://dsdmoj.atlassian.net/browse/LNP-1140
N/A
Add the php-spx extension into the local docker container running Drupal.
This allows us to profile the application to identify potential areas to improve performance.
Compiles and includes the latest release of php-spx when building the local docker container.
Configures it to allow local connection.
No
No
No
> LNP-1140: ⚡️ add php-spx to local docker build to allow application profiling
